New universal version, determines file type and calls appropriate translator
git-svn-id: https://svn.code.sf.net/p/plexil/code/trunk@1582 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/bin/plexilc b/bin/plexilc
--- a/bin/plexilc
+++ b/bin/plexilc
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright (c) 2006-2008, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2010, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -25,9 +25,47 @@
 # TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+#
+# Usage:
+#    plexilc [options] <source-file>
+#
+# where options are:
+#
+#    -d, -debug <filename>     Print debug information to filename
+#    -h, -help                 Print this help and exit
+#    -o, -output <filename>    Write translator output to filename
+#    -q, -quiet                Parse files quietly
+#    -c, -check                Run static checker, if source file is a plan
+#    -v, -version              Print the translator version and exit
+#
+#  The type of source file given is partly identified by its extension:
+#
+#    Plexil plans and scripts     : .ple
+#    Plexilisp plans and scripts  : .pli
+#
+#  Note that a .ple file must have its content inspected to see if it's a plan or
+#  script.  The default (and required) output file extensions will be:
+#
+#    Plexil plans (XML)                    : .plx
+#    Plexil scripts (XML)                  : .pls
+#
+
+function usage ()
+{
+	echo "Usage: $0 [options] <source-file>"
+    echo "Options are"
+	echo "  -c, -check              Run static checker on output (only valid for plan files)"
+    echo "  -d, -debug <logfile>    Print debug information to <logfile>"
+    echo "  -h, -help               Print this help and exit"
+	echo "  -o, -output <outfile>   Write translator output to <outfile>"
+	echo "  -q, -quiet              Parse files quietly"
+	echo "  -v, -version            Print translator version and exit"
+	echo "Some options are not supported for all file formats."
+}
+
 # Check environment variables
 if [ ! $PLEXIL_HOME ]
-  then
+then
     echo Error: Please set environment variable PLEXIL_HOME
     echo to the full pathname of your 'plexil' or 'trunk' directory.
     exit 1
@@ -36,6 +74,140 @@ fi
 . ${PLEXIL_HOME}/bin/plexil-setup.sh
 
 JARS_DIR=${PLEXIL_HOME}/third-party/jars
+LIB_DIR=${PLEXIL_HOME}/lib
 
-# Assumes pathnames relative to $PLEXIL_HOME
-java -cp ${PLEXIL_HOME}/lib/plexil.jar:${JARS_DIR}/antlr.jar:${JARS_DIR}/nanoxml.jar:${JARS_DIR}/saxon.jar plexil.Parse $*
+# Commands to execute
+plexil_compiler="java -cp ${LIB_DIR}/plexil.jar:${JARS_DIR}/antlr.jar:${JARS_DIR}/nanoxml.jar:${JARS_DIR}/saxon.jar plexil.Parse"
+plexilscript_compiler="java -cp ${LIB_DIR}/plexilscript.jar:${JARS_DIR}/antlr.jar plexilscript.PlexilScriptParse"
+plexil_checker="$PLEXIL_HOME/src/checker/checkDecls"
+
+# Parse options
+while [ "${1:0:1}" = '-' ]
+do
+	if [ "$1" = '-c' -o "$1" = '-check' ]
+	then
+		check=$1
+		shift
+	elif [ "$1" = '-d' -o "$1" = '-debug' ]
+	then
+		if [ -z "$2" -o "${2:0:1}" = '-' ]
+		then
+			echo "Error: debug filename missing for $1 option"
+			usage
+			exit 1
+		fi
+		debug=$2
+		shift 2
+	elif [ "$1" = '-h' -o "$1" = '-help' ]
+	then
+		usage
+		exit 0
+	elif [ "$1" = '-o' -o "$1" = '-output' ]
+	then
+		if [ -z "$2" -o "${2:0:1}" = '-' ]
+		then
+			echo "Error: output filename missing for $1 option"
+			usage
+			exit 1
+		fi
+		output=$2
+		shift 2
+	elif [ "$1" = '-q' -o "$1" = '-quiet' ]
+	then
+		quiet=$1
+		shift
+	elif [ "$1" = '-v' -o "$1" = '-version' ]
+	then
+		echo 'plexilc script version 1.0'
+		$plexil_compiler --version
+		exit 0
+	fi
+done
+
+# If we got this far, we are expecting a filename to translate
+if [ $# -lt 1 ]
+then
+	echo "Error: no filename supplied."
+	usage
+	exit 1
+fi
+
+if [ ! -r $1 ]
+then
+	echo "Error: file $1 does not exist or is not readable"
+	exit 1
+fi
+
+# Select translator for this file
+if [ `expr $1 : '.*\.ple\$'` -ne 0 ]
+then
+	# Plexil plan
+	options=""
+	if [ -n "$debug" ]
+	then
+		options="$options -d $debug" 
+	fi
+	if [ -n "$quiet" ]
+	then
+		options="$options -q"
+	fi
+
+	if [ -z "$output" ]
+	then
+		output=${1//\.ple/.plx}
+	fi
+
+	$plexil_compiler $options -o $output $1
+
+	if [ -n "$check" ]
+	then
+		$plexil_checker $output
+	fi
+
+elif [ `expr $1 : '.*\.pli\$'` -ne 0 ]
+then
+	# Plexilisp plan/script
+
+	if [ -n "$quiet" ]
+	then
+		emacs --batch --no-site-file --load $PLEXIL_HOME/src/plexilisp/plexil.el $1 --eval '(plexil)' > /dev/null 2>&1
+	else
+		emacs --batch --no-site-file --load $PLEXIL_HOME/src/plexilisp/plexil.el $1 --eval '(plexil)'
+	fi
+
+	# If plexilisp generates a plan, we can check it.
+	output=${1//\.pli/.plx}
+	if [ -r $output -a -n "$check" ]
+	then
+		$plexil_checker $output
+	fi
+
+elif [ `expr $1 : '.*\.epx\$'` -ne 0 ]
+then
+	# Extended Plexil XML plan
+
+	output=${1//\.epx/.plx}
+	$PLEXIL_HOME/bin/eplexil $1 $output
+
+	if [ -n "$check" ]
+	then
+		$plexil_checker $output
+	fi
+
+elif [ `expr $1 : '.*\.pst\$'` -ne 0 ]
+then
+	# Plexilscript
+	if [ -z "$output" ]
+	then
+		output=${1//\.pst/.psx}
+	fi
+	$plexilscript_compiler < $1 > $output
+else
+	echo "Error: file $1 not recognized."
+	echo "Recognized extensions are:"
+	echo "  .epx - Extended Plexil XML plan"
+	echo "  .ple - Plexil plan"
+	echo "  .pli - Plexilisp plan or simulation script"
+	echo "  .pst - Plexilscript simulation script"
+	exit 1
+fi
