Backport compiler test infrastructure from plexil-x
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@5263 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/compilers/plexil/test/check b/compilers/plexil/test/check
--- a/compilers/plexil/test/check
+++ b/compilers/plexil/test/check
@@ -1,1 +1,72 @@
-diff valid/valid-$1.epx output/$1.epx
+#! /bin/sh
+
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+#     * Redistributions of source code must retain the above copyright
+#       notice, this list of conditions and the following disclaimer.
+#     * Redistributions in binary form must reproduce the above copyright
+#       notice, this list of conditions and the following disclaimer in the
+#       documentation and/or other materials provided with the distribution.
+#     * Neither the name of the Universities Space Research Association nor the
+#       names of its contributors may be used to endorse or promote products
+#       derived from this software without specific prior written permission.
+#
+# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
+# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
+# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
+# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
+# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
+# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
+# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
+outfile="output/$1.epx"
+validfile="valid/valid-$1.epx"
+
+if [ ! -r "$outfile" ]
+then
+    echo "$0: Error: Output file $outfile was not found or is not readable." >&2
+    exit 1
+fi
+
+if [ ! -r "$validfile" ]
+then
+    echo "$0: Error: Valid file $validfile was not found or is not readable." >&2
+    exit 1
+fi
+
+# Create named FIFOs for the formatted output
+outfmt="/tmp/$1.epx.fmt"
+validfmt="/tmp/valid-$1.epx.fmt"
+
+rm -f "$outfmt" "$validfmt"
+
+if ! mkfifo "$outfmt" "$validfmt"
+then
+    echo "$0: Error: mkfifo failed. Exiting." >&2
+    exit 1
+fi
+
+trap cleanup 1 2 3 6
+
+cleanup()
+{
+    rm -f "$outfmt" "$validfmt"
+    echo "Exiting due to error." >&2
+    exit 1
+}
+
+xmllint --format "$outfile" > "$outfmt" &
+xmllint --format "$validfile" > "$validfmt" &
+
+diff -B -w "$outfmt" "$validfmt"
+result=$?
+
+rm -f "$outfmt" "$validfmt"
+
+exit $result
diff --git a/compilers/plexil/test/compile-validate b/compilers/plexil/test/compile-validate
--- a/compilers/plexil/test/compile-validate
+++ b/compilers/plexil/test/compile-validate
@@ -1,5 +1,13 @@
 #! /bin/sh
 
+# Run the Standard Plexil compiler on one regression test case,
+# and check the output generated against the XML schema,
+# and (if it exists) a "known good" file.
+# Exit with 0 status if all OK. Exit with 1 status if not.
+# Writes results to tempRegressionResults in the current working directory.
+
+# Expects to be run from $PLEXIL_HOME/compilers/plexil/test
+
 # Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
@@ -28,8 +36,8 @@
 # Check environment variables
 if [ ! "$PLEXIL_HOME" ]
 then
-    echo Error: Please set environment variable PLEXIL_HOME
-    echo to the full pathname of your 'plexil' or 'trunk' directory.
+    echo "Error: Please set environment variable PLEXIL_HOME"
+    echo "to the full pathname of your 'plexil' or 'trunk' directory."
     exit 1
 fi
 
@@ -37,24 +45,35 @@ fi
 . "$PLEXIL_HOME"/scripts/plexil-setup.sh
 
 SCHEMA_DIR="$PLEXIL_HOME"/schema
-PLEXIL_COMPILER_DIR="$PLEXIL_HOME"/compilers/plexil
+EPX_SCHEMA="$SCHEMA_DIR"/extended-plexil.xsd
 
-OUTFILE=output/"$(basename "$1" .ple)".epx
-
-# Generate 
-
-if ! "$PLEXIL_COMPILER_DIR"/PlexilCompiler --epx-only -o "$OUTFILE" "$1"
+if ! ../PlexilCompiler --epx-only -o output/"$1".epx input/"$1".ple
 then
-	echo "Compilation of $1 failed."
-	exit 1
+	echo "*** Compilation of $1.ple failed ***" >> tempRegressionResults
+	echo "*** Compilation of $1.ple failed ***"
+    exit 1
 fi
 
-# Validate, redirecting output to stderr
-
-if ! xmllint --noout --schema "$SCHEMA_DIR"/extended-plexil.xsd "$OUTFILE" 1>&2
+if ! xmllint --noout --schema "$EPX_SCHEMA" output/"$1".epx 2>>tempRegressionResults 1>&2 
 then
-	echo "Validation of $OUTFILE failed."
-	exit 1
-fi
+	echo "*** Validation of $1.epx failed ***" >> tempRegressionResults 
+	echo "*** Validation of $1.epx failed ***" 
+    exit 1
+fi 
+
+if [ -f valid/valid-"$1".epx ]
+then 
+	if "$PLEXIL_HOME"/compilers/plexil/test/check "$1" >> tempRegressionResults
+    then
+		echo "Verified $1.epx" >> tempRegressionResults 
+		echo "Verified $1.epx" 
+	else
+		echo "*** Verification of $1.epx failed ***" >> tempRegressionResults 
+		echo "*** Verification of $1.epx failed ***" 
+        exit 1
+	fi 
+else
+	echo "Validated $1.epx; no valid file, skipping verification" 
+fi 
 
 exit 0
