Fix issues turned up by shellcheck
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-x@5215 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/compilers/plexil/test/validate b/compilers/plexil/test/validate
--- a/compilers/plexil/test/validate
+++ b/compilers/plexil/test/validate
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -26,34 +26,34 @@
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 # Check environment variables
-if [ ! $PLEXIL_HOME ]
+if [ ! "$PLEXIL_HOME" ]
 then
     echo Error: Please set environment variable PLEXIL_HOME
     echo to the full pathname of your 'plexil' or 'trunk' directory.
     exit 1
 fi
 
-. ${PLEXIL_HOME}/scripts/plexil-setup.sh
+# shellcheck source=../../../scripts/plexil-setup.sh
+. "$PLEXIL_HOME"/scripts/plexil-setup.sh
 
-SCHEMA_DIR=${PLEXIL_HOME}/schema
-PLEXIL_COMPILER_DIR=${PLEXIL_HOME}/compilers/plexil
+SCHEMA_DIR="$PLEXIL_HOME"/schema
+PLEXIL_COMPILER_DIR="$PLEXIL_HOME"/compilers/plexil
 
-OUTEPX=${1/%.ple/.epx}
-OUTFILE=${OUTEPX/input/output}
+OUTFILE=output/"$(basename "$1" .ple)".epx
 
 # Generate 
-${PLEXIL_COMPILER_DIR}/PlexilCompiler --epx-only -o ${OUTFILE} $1
-if [ $? -ne 0 ]
+
+if ! "$PLEXIL_COMPILER_DIR"/PlexilCompiler --epx-only -o "$OUTFILE" "$1"
 then
-	echo Compilation of $1 failed.
+	echo "Compilation of $1 failed."
 	exit 1
 fi
 
 # Validate, redirecting output to stderr
-xmllint --noout --schema ${SCHEMA_DIR}/extended-plexil.xsd ${OUTFILE} 1>&2
-if [ $? -ne 0 ]
+
+if ! xmllint --noout --schema "$SCHEMA_DIR"/extended-plexil.xsd "$OUTFILE" 1>&2
 then
-	echo Validation of ${OUTFILE} failed.
+	echo "Validation of $OUTFILE failed."
 	exit 1
 fi
 
