Switch TestExec regression test scripts to /bin/sh from bash; add bulletproofing; remove two shell scripts no longer in use

diff --git a/test/TestExec-regression-test/run-empty-script-valid-test b/test/TestExec-regression-test/run-empty-script-valid-test
--- a/test/TestExec-regression-test/run-empty-script-valid-test
+++ b/test/TestExec-regression-test/run-empty-script-valid-test
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -27,47 +27,47 @@
 
 if [ -z "$1" ]
 then
-   echo "Usage: $0 <test_name>"
+   echo "Usage: $0 <test_name>" >&2
    exit 1
 fi
 
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo "$0: Environment variable PLEXIL_HOME not set"
+    echo "$0: Environment variable PLEXIL_HOME not set" >&2
     exit 1
 fi
 
-. ${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh
-cd $TEST_DIR
+. "${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh"
+cd "$TEST_DIR"
 
-PLAN_FILE=plans/$1.plx
-if [ ! -r $PLAN_FILE ]
+PLAN_FILE="plans/$1.plx"
+if [ ! -r "$PLAN_FILE" ]
 then
-   echo "$0: Plan file $PLAN_FILE not found"
+   echo "$0: Plan file $PLAN_FILE not found" >&2
    exit 1
 fi
 
-VALID_FILE=valid/RUN_$1_empty-script.valid
-if [ ! -r $VALID_FILE ]
+VALID_FILE="valid/RUN_$1_empty-script.valid"
+if [ ! -r "$VALID_FILE" ]
 then
-   echo "$0: Valid file $VALID_FILE not found"
+   echo "$0: Valid file $VALID_FILE not found" >&2
    exit 1
 fi
 
-OUT_FILE=output/$1.out
+OUT_FILE="output/$1.out"
 
-echo $1 >> tempRegressionResults
-$EXEC_PROG -d $TEST_DEBUG_CFG -p $PLAN_FILE -s $EMPTY_SCRIPT > $OUT_FILE 2>> tempRegressionResults
-declare -i execstatus=$?
+echo "$1" >> tempRegressionResults
+"$EXEC_PROG" -d "$TEST_DEBUG_CFG" -p "$PLAN_FILE" -s "$EMPTY_SCRIPT" > "$OUT_FILE" 2>> tempRegressionResults
+execstatus=$?
 if [ $execstatus -gt 128 ]
 then
-    declare -i sig=$execstatus-128
-    echo '***' Test $1 exited on signal $sig >> RegressionResults
-    echo '***' Test $1 exited on signal $sig
+    sig=$execstatus-128
+    echo "*** Test $1 exited on signal $sig" >> RegressionResults
+    echo "*** Test $1 exited on signal $sig" >&2
 elif [ $execstatus -ne 0 ]
 then
-    echo '***' Test $1 exited with status $execstatus >> RegressionResults
-    echo '***' Test $1 exited with status $execstatus
+    echo "*** Test $1 exited with status $execstatus" >> RegressionResults
+    echo "*** Test $1 exited with status $execstatus" >&2
 fi
 
-perl $REGRESSION_PL $OUT_FILE $VALID_FILE
+exec perl "$REGRESSION_PL" "$OUT_FILE" "$VALID_FILE"
diff --git a/test/TestExec-regression-test/run-tests b/test/TestExec-regression-test/run-tests
--- a/test/TestExec-regression-test/run-tests
+++ b/test/TestExec-regression-test/run-tests
@@ -1,7 +1,7 @@
-#! /usr/bin/env bash
+#! /bin/sh
 # Run all TestExec regression tests
 
-# Copyright (c) 2006-2017, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -28,14 +28,26 @@
 
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo "$0: Environment variable PLEXIL_HOME not set"
+    # Attempt to guess location of this script (but don't try too hard)
+    PLEXIL_TEST_DIR="$( cd "$(dirname "$(command -v "$0")")" && cd .. && pwd -P )"
+    if [ "test" = "$(basename "$PLEXIL_TEST_DIR")" ]
+    then
+        export PLEXIL_HOME="$(dirname "$PLEXIL_TEST_DIR")"
+    fi
+    unset PLEXIL_TEST_DIR
+fi
+
+if [ -z "$PLEXIL_HOME" ]
+then
+    echo 'Error: Please set environment variable PLEXIL_HOME' >&2
+    echo "to the full pathname of your 'plexil' or 'trunk' directory." >&2
     exit 1
 fi
 
 . ${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh
 
 # Parser error detection tests
-PARSER_ERROR_TESTS=`(cd ${TEST_DIR}/plans/parser-tests; ls *.plx | sed -e 's/.plx//g')`
+PARSER_ERROR_TESTS="$(cd "${TEST_DIR}/plans/parser-tests"; ls *.plx | sed -e 's/.plx//g')"
 
 # Tests requiring no external interaction, for which root node success is sufficient
 EMPTY_SCRIPT_TESTS='AncestorReferenceTest array2 array5 array6 array9
@@ -88,9 +100,9 @@ RESOURCE_ARBITRATION_TESTS='resource1 Resource1RepeatCond
 # Simple-drive tests
 SIMPLE_DRIVE_SCRIPTS='single-drive double-drive'
 
-export PATH=${TEST_DIR}:${PATH}
+export PATH="${TEST_DIR}:${PATH}"
 
-cd ${TEST_DIR}
+cd "${TEST_DIR}"
 
 # Make temp output directory if needed
 mkdir -p output
diff --git a/test/TestExec-regression-test/run-xml-parser-test b/test/TestExec-regression-test/run-xml-parser-test
--- a/test/TestExec-regression-test/run-xml-parser-test
+++ b/test/TestExec-regression-test/run-xml-parser-test
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -27,29 +27,29 @@
 
 if [ -z "$1" ]
 then
-   echo "Usage: $0 <test_name>"
+   echo "Usage: $0 <test_name>" >&2
    exit 1
 fi
 
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo "$0: Environment variable PLEXIL_HOME not set"
+    echo "$0: Environment variable PLEXIL_HOME not set" >&2
     exit 1
 fi
 
-. ${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh
+. "${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh"
 
-PLAN_FILE=${TEST_DIR}/plans/parser-tests/$1.plx
-if [ ! -r $PLAN_FILE ]
+PLAN_FILE="${TEST_DIR}/plans/parser-tests/$1.plx"
+if [ ! -r "$PLAN_FILE" ]
 then
-   echo "$0: Plan file $PLAN_FILE not found"
+   echo "$0: Plan file $PLAN_FILE not found" >&2
    exit 1
 fi
 
-OUT_FILE=${TEST_DIR}/output/$1.out
+OUT_FILE="${TEST_DIR}/output/$1.out"
 
-echo $1 >> ${TEST_DIR}/tempRegressionResults
-if $EXEC_PROG -p $PLAN_FILE -s $EMPTY_SCRIPT > $OUT_FILE 2>&1
+echo "$1" >> "${TEST_DIR}/tempRegressionResults"
+if "$EXEC_PROG" -p "$PLAN_FILE" -s "$EMPTY_SCRIPT" > "$OUT_FILE" 2>&1
 then
-    echo $1: Failed to detect expected parser error
+    echo "$1: Failed to detect expected parser error" >&2
 fi
