Convert regression test shell scripts to portable POSIX shell syntax; fix all potential errors identified by shellcheck
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-x@5210 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/test/TestExec-regression-test/run-empty-script-test b/test/TestExec-regression-test/run-empty-script-test
--- a/test/TestExec-regression-test/run-empty-script-test
+++ b/test/TestExec-regression-test/run-empty-script-test
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -37,31 +37,32 @@ then
     exit 1
 fi
 
-. ${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh
-cd $TEST_DIR
+# shellcheck source=test-env.sh
+. "$PLEXIL_HOME"/test/TestExec-regression-test/test-env.sh
+cd "$TEST_DIR" || (echo "$0: Unable to change to $TEST_DIR; exiting" ; exit 1)
 
-PLAN_FILE=plans/$1.plx
-if [ ! -r $PLAN_FILE ]
+PLAN_FILE="plans/$1.plx"
+if [ ! -r "$PLAN_FILE" ]
 then
-   echo "$0: Plan file $PLAN_FILE not found"
+   echo "$0: Plan file $PLAN_FILE not found ; exiting"
    exit 1
 fi
 
-OUT_FILE=output/$1.out
+OUT_FILE="output/$1.out"
 
-echo $1 >> tempRegressionResults
-$EXEC_PROG -L plans -d $TEST_DEBUG_CFG -p $PLAN_FILE -s $EMPTY_SCRIPT > $OUT_FILE 2>> tempRegressionResults
-declare -i execstatus=$?
+echo "$1" >> tempRegressionResults
+"$EXEC_PROG" -L plans -d "$TEST_DEBUG_CFG" -p "$PLAN_FILE" -s "$EMPTY_SCRIPT" > "$OUT_FILE" 2>> tempRegressionResults
+execstatus=$?
 if [ $execstatus -gt 128 ]
 then
-    declare -i sig=$execstatus-128
-    echo '***' Test $1 exited on signal $sig >> RegressionResults
-    echo '***' Test $1 exited on signal $sig
+    sig=$execstatus-128
+    echo "*** Test $1 exited on signal $sig" >> RegressionResults
+    echo "*** Test $1 exited on signal $sig"
 elif [ $execstatus -ne 0 ]
 then
-    echo '***' Test $1 exited with status $execstatus >> RegressionResults
-    echo '***' Test $1 exited with status $execstatus
+    echo "*** Test $1 exited with status $execstatus" >> RegressionResults
+    echo "*** Test $1 exited with status $execstatus"
 fi
 
-perl $REGRESSION_PL $OUT_FILE
+perl "$REGRESSION_PL" "$OUT_FILE"
 
diff --git a/test/TestExec-regression-test/run-tests b/test/TestExec-regression-test/run-tests
--- a/test/TestExec-regression-test/run-tests
+++ b/test/TestExec-regression-test/run-tests
@@ -1,7 +1,7 @@
-#! /usr/bin/env bash
+#! /bin/sh
 # Run all TestExec regression tests
 
-# Copyright (c) 2006-2017, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -32,10 +32,11 @@ then
     exit 1
 fi
 
-. ${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh
+# shellcheck source=test-env.sh
+. "$PLEXIL_HOME"/test/TestExec-regression-test/test-env.sh
 
 # Parser error detection tests
-PARSER_ERROR_TESTS=`(cd ${TEST_DIR}/plans/parser-tests; ls *.plx | sed -e 's/.plx//g')`
+PARSER_ERROR_TESTS="$(find "$TEST_DIR"/plans/parser-tests -name '*.plx' -depth 1 -exec basename {} .plx \;)"
 
 # Tests requiring no external interaction, for which root node success is sufficient
 EMPTY_SCRIPT_TESTS='AncestorReferenceTest array2 array5 array6 array9
@@ -87,9 +88,9 @@ RESOURCE_ARBITRATION_TESTS='resource1 Resource1RepeatCond
 # Simple-drive tests
 SIMPLE_DRIVE_SCRIPTS='single-drive double-drive'
 
-export PATH=${TEST_DIR}:${PATH}
+export PATH="$TEST_DIR":"$PATH"
 
-cd ${TEST_DIR}
+cd "$TEST_DIR" || ( echo "$0: Unable to change to $TEST_DIR ; exiting" ; exit 1 )
 
 # Make temp output directory if needed
 mkdir -p output
@@ -105,11 +106,11 @@ echo
 echo --------------------- SUMMARY OF FAILED TESTS ---------------------
 echo
 
-for test in $PARSER_ERROR_TESTS ; do run-xml-parser-test $test ; done
-for test in $EMPTY_SCRIPT_TESTS ; do run-empty-script-test $test ; done
-for test in $EMPTY_SCRIPT_VALID_TESTS ; do run-empty-script-valid-test $test ; done
-for test in $SAME_NAME_SCRIPT_TESTS ; do run-same-name-script-test $test ; done
-for script in $SIMPLE_DRIVE_SCRIPTS ; do run-simple-drive-test $script ; done
+for test in $PARSER_ERROR_TESTS ; do run-xml-parser-test "$test" ; done
+for test in $EMPTY_SCRIPT_TESTS ; do run-empty-script-test "$test" ; done
+for test in $EMPTY_SCRIPT_VALID_TESTS ; do run-empty-script-valid-test "$test" ; done
+for test in $SAME_NAME_SCRIPT_TESTS ; do run-same-name-script-test "$test" ; done
+for script in $SIMPLE_DRIVE_SCRIPTS ; do run-simple-drive-test "$script" ; done
 
 # Command handles tests
 for openclosed in open closed
@@ -118,21 +119,21 @@ do
     do
         for script_scenario in a1 a3
         do
-            plan=simple-${openclosed}loop-command-${plan_scenario}
-            script=simple-${openclosed}loop-command-${script_scenario}
-            run-scripted-valid-test $plan $script
+            plan=simple-"$openclosed"loop-command-"$plan_scenario"
+            script=simple-"$openclosed"loop-command-"$script_scenario"
+            run-scripted-valid-test "$plan" "$script"
         done
     done
 done
 run-scripted-valid-test simple-openloop-command-nopost simple-openloop-command-a3
 run-same-name-script-valid-test simple-closedloop-command-multipleAck
 
-for test in $RESOURCE_ARBITRATION_TESTS ; do run-same-name-script-valid-test $test ; done
-for test in $LIBRARY_TESTS ; do run-empty-script-test $test ; done
+for test in $RESOURCE_ARBITRATION_TESTS ; do run-same-name-script-valid-test "$test" ; done
+for test in $LIBRARY_TESTS ; do run-empty-script-test "$test" ; done
 
 # Output footer to console
 echo
-echo ------------------- END SUMMARY OF FAILED TESTS ------------------- 
-echo -- for complete test results see file: RegressionResults 
+echo "------------------- END SUMMARY OF FAILED TESTS -------------------"
+echo "-- for complete test results see file: RegressionResults"
 echo
 
diff --git a/test/TestExec-regression-test/run-xml-parser-test b/test/TestExec-regression-test/run-xml-parser-test
--- a/test/TestExec-regression-test/run-xml-parser-test
+++ b/test/TestExec-regression-test/run-xml-parser-test
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -33,23 +33,26 @@ fi
 
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo "$0: Environment variable PLEXIL_HOME not set"
+    echo "$0: Environment variable PLEXIL_HOME not set; exiting"
     exit 1
 fi
 
-. ${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh
+# shellcheck source=test-env.sh
+. "$PLEXIL_HOME"/test/TestExec-regression-test/test-env.sh
+cd "$TEST_DIR" || ( echo "$0: Unable to change to $TEST_DIR ; exiting" ; exit 1 )
 
-PLAN_FILE=${TEST_DIR}/plans/parser-tests/$1.plx
-if [ ! -r $PLAN_FILE ]
+PLAN_FILE=plans/parser-tests/"$1".plx
+if [ ! -r "$PLAN_FILE" ]
 then
-   echo "$0: Plan file $PLAN_FILE not found"
+   echo "$0: Plan file $PLAN_FILE not found; exiting"
    exit 1
 fi
 
-OUT_FILE=${TEST_DIR}/output/$1.out
+OUT_FILE=output/"$1".out
 
-echo $1 >> ${TEST_DIR}/tempRegressionResults
-if $EXEC_PROG -p $PLAN_FILE -s $EMPTY_SCRIPT > $OUT_FILE 2>&1
+echo "$1" >> tempRegressionResults
+if "$EXEC_PROG" -p "$PLAN_FILE" -s "$EMPTY_SCRIPT" > "$OUT_FILE" 2>&1
 then
-    echo $1: Failed to detect expected parser error
+    echo "$0: Failed to detect expected parser error in $1.plx"
+    exit 1
 fi
diff --git a/test/TestExec-regression-test/v1-v2-conversion-test b/test/TestExec-regression-test/v1-v2-conversion-test
--- a/test/TestExec-regression-test/v1-v2-conversion-test
+++ b/test/TestExec-regression-test/v1-v2-conversion-test
@@ -1,7 +1,7 @@
-#! /usr/bin/env bash
+#! /bin/sh
 # Run all TestExec regression tests on both original and doubly converted plans
 
-# Copyright (c) 2006-2016, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -32,41 +32,42 @@ then
     exit 1
 fi
 
-. ${PLEXIL_HOME}/test/TestExec-regression-test/test-env.sh
+# shellcheck source=test-env.sh
+. "$PLEXIL_HOME"/test/TestExec-regression-test/test-env.sh
 
-schema_dir="${PLEXIL_HOME}/schema"
-export PATH=${TEST_DIR}:${PATH}:${schema_dir}/test
+schema_dir="$PLEXIL_HOME"/schema
+export PATH="$TEST_DIR":"$PATH":"$schema_dir"/test
 
 conversion_dir=/tmp/plexil/plans
 
 original_planfile()
 {
-    echo "${TEST_DIR}/plans/$1.plx"
+    echo "$TEST_DIR/plans/$1.plx"
 }
 
 v1_planfile()
 {
-    echo "${conversion_dir}/$1.px1"
+    echo "$conversion_dir/$1.px1"
 }
 
 v2_planfile()
 {
-    echo "${conversion_dir}/$1.px2"
+    echo "$conversion_dir/$1.px2"
 }
 
 script_file()
 {
-    echo "${TEST_DIR}/scripts/$1.psx"
+    echo "$TEST_DIR/scripts/$1.psx"
 }
 
 original_outfile()
 {
-    echo "${TEST_DIR}/output/$1.out"
+    echo "$TEST_DIR/output/$1.out"
 }
 
 converted_outfile()
 {
-    echo "${TEST_DIR}/output/$1.converted.out"
+    echo "$TEST_DIR/output/$1.converted.out"
 }
 
 empty_script_valid_file()
@@ -76,20 +77,20 @@ empty_script_valid_file()
 
 convert()
 {
-    mkdir -p "${conversion_dir}"
-    v2=`v2_planfile $1`
-    saxon "${schema_dir}/plexil-v1-to-v2.xsl" `original_planfile $1` "${v2}"
-    if [ ! -r "${v2}" ]
+    mkdir -p "$conversion_dir"
+    v2="$(v2_planfile $1)"
+    saxon "$schema_dir/plexil-v1-to-v2.xsl" "$(original_planfile $1)" "$v2"
+    if [ ! -r "$v2" ]
     then
-        echo '***' Conversion of plan $1 to PLEXIL V2 failed
+        echo "*** Conversion of plan $1 to PLEXIL V2 failed"
         return 1
     fi
     
-    v1=`v1_planfile $1`
-    saxon "${schema_dir}/plexil-v2-to-v1.xsl" "${v2}" "${v1}"
-    if [ ! -r "${v1}" ]
+    v1="$(v1_planfile "$1")"
+    saxon "$schema_dir/plexil-v2-to-v1.xsl" "$v2" "$v1"
+    if [ ! -r "$v1" ]
     then
-        echo '***' Conversion of plan $1 from PLEXIL V2 back to PLEXIL V1 failed
+        echo "*** Conversion of plan $1 from PLEXIL V2 back to PLEXIL V1 failed"
         return 1
     fi
 
@@ -99,53 +100,53 @@ convert()
 # Shamelessly copied from script file of same name
 run_empty_script_test()
 {
-    PLAN_FILE=`original_planfile "$1"`
-    if [ ! -r $PLAN_FILE ]
+    PLAN_FILE="$(original_planfile "$1")"
+    if [ ! -r "$PLAN_FILE" ]
     then
         echo "$0: Plan file $PLAN_FILE not found"
         return 1
     fi
 
-    OUT_FILE=`original_outfile "$1"`
+    OUT_FILE="$(original_outfile "$1")"
 
-    echo $1 >> tempConversionResults
-    $EXEC_PROG -L plans -d $TEST_DEBUG_CFG -p $PLAN_FILE -s $EMPTY_SCRIPT > $OUT_FILE 2>> tempConversionResults
-    declare -i execstatus=$?
+    echo "$1" >> tempConversionResults
+    "$EXEC_PROG" -L plans -d "$TEST_DEBUG_CFG" -p "$PLAN_FILE" -s "$EMPTY_SCRIPT" > "$OUT_FILE" 2>> tempConversionResults
+    execstatus=$?
     if [ $execstatus -gt 128 ]
     then
-        declare -i sig=$execstatus-128
-        echo '***' Test $1 exited on signal $sig >> ConversionResults
-        echo '***' Test $1 exited on signal $sig
+        sig=$execstatus-128
+        echo "*** Test $1 exited on signal $sig" >> ConversionResults
+        echo "*** Test $1 exited on signal $sig"
     elif [ $execstatus -ne 0 ]
     then
-        echo '***' Test $1 exited with status $execstatus >> ConversionResults
-        echo '***' Test $1 exited with status $execstatus
+        echo "*** Test $1 exited with status $execstatus" >> ConversionResults
+        echo "*** Test $1 exited with status $execstatus"
     fi
 
-    perl $REGRESSION_PL $OUT_FILE
+    perl "$REGRESSION_PL" "$OUT_FILE"
 }
 
 compare_empty_script_test()
 {
-    OUT_FILE_BEFORE=`original_outfile "$1"`
-    OUT_FILE_AFTER=`converted_outfile "$1"`
+    OUT_FILE_BEFORE="$(original_outfile "$1")"
+    OUT_FILE_AFTER="$(converted_outfile "$1")"
 
-    PLAN_FILE_AFTER=`v1_planfile "$1"`
+    PLAN_FILE_AFTER="$(v1_planfile "$1")"
 
-    $EXEC_PROG -L "${conversion_dir}" -d $TEST_DEBUG_CFG -p $PLAN_FILE_AFTER -s $EMPTY_SCRIPT > $OUT_FILE_AFTER 2>> tempConversionResults
-    declare -i execstatus=$?
+    "$EXEC_PROG" -L "$conversion_dir" -d "$TEST_DEBUG_CFG" -p "$PLAN_FILE_AFTER" -s "$EMPTY_SCRIPT" > "$OUT_FILE_AFTER" 2>> tempConversionResults
+    execstatus=$?
     if [ $execstatus -gt 128 ]
     then
-        declare -i sig=$execstatus-128
-        echo '***' Test $1 exited on signal $sig >> ConversionResults
-        echo '***' Test $1 exited on signal $sig
+        sig=$execstatus-128
+        echo "*** Test $1 exited on signal $sig" >> ConversionResults
+        echo "*** Test $1 exited on signal $sig"
     elif [ $execstatus -ne 0 ]
     then
-        echo '***' Test $1 exited with status $execstatus >> ConversionResults
-        echo '***' Test $1 exited with status $execstatus
+        echo "*** Test $1 exited with status $execstatus" >> ConversionResults
+        echo "*** Test $1 exited with status $execstatus"
     fi
 
-    perl $REGRESSION_PL $OUT_FILE_AFTER $OUT_FILE_BEFORE
+    perl "$REGRESSION_PL" "$OUT_FILE_AFTER" "$OUT_FILE_BEFORE"
 }
 
 compare_empty_script_valid_test()
