Merge back Extended Plexil validation test improvements from plexil-x branch
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@4539 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/schema/test/Makefile b/schema/test/Makefile
--- a/schema/test/Makefile
+++ b/schema/test/Makefile
@@ -1,5 +1,31 @@
+# Copyright (c) 2006-2016, Universities Space Research Association (USRA).
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+#     * Redistributions of source code must retain the above copyright
+#       notice, this list of conditions and the following disclaimer.
+#     * Redistributions in binary form must reproduce the above copyright
+#       notice, this list of conditions and the following disclaimer in the
+#       documentation and/or other materials provided with the distribution.
+#     * Neither the name of the Universities Space Research Association nor the
+#       names of its contributors may be used to endorse or promote products
+#       derived from this software without specific prior written permission.
+#
+# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
+# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
+# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
+# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
+# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
+# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
+# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
 # Translates Extended PLEXIL test files into Core PLEXIL, placing the
-# output in the 'translated' subdirectory.
+# output in the 'output' subdirectory, and compares them with the
+# "gold standard" files in the 'verified' subdirectory.
 
 SHELL = /bin/sh
 
@@ -22,9 +48,11 @@ REST = UncheckedSequence1 UncheckedSequence2 \
 
 TESTS = $(SYNCH) $(REST)
 
+PLEXIL_HOME ?= ../..
 
-# Temporary file
-DIFF = /tmp/plexil-$$$$
+EPLEXIL = ../../scripts/eplexil
+
+LOG = verify.out
 
 default: test
 
@@ -32,26 +60,35 @@ output:
 	@ mkdir -p $@
 
 test: output
-	@ test_failed=0; \
+	@ export PLEXIL_HOME="$(PLEXIL_HOME)"; \
+	rm -f $(LOG) ; touch $(LOG) ; \
+	test_failed=0; \
 	for i in $(TESTS); do \
-		eplexil input/$$i.epx output/$$i.plx ; \
+		echo "$$i" >> $(LOG) ; \
+		$(EPLEXIL) input/$$i.epx output/$$i.plx ; \
 		if [ $$? -ne 0 ] ; then \
 			test_failed=1 ; \
-			echo "*** Translation of input/$$i.epx failed ***" ;\
+			echo "*** Translation of input/$$i.epx failed ***" >> $(LOG) ; \
+			echo "*** Translation of input/$$i.epx failed ***" ; \
 			exit 1 ; \
 		fi ; \
-		xmllint --noout --schema ../core-plexil.xsd output/$$i.plx ; \
-		if [ $$? -ne 0 ] ; then test_failed=1 ; fi ; \
-		diff output/$$i.plx verified/verified-$$i.plx \
-		  > $(DIFF) ; \
-		diffsize=`wc $(DIFF) | awk '{print $$1}'` ; \
-		if [ $$diffsize -ne 0 ] ; then \
-			test_failed=1 ; \
-			echo "*** output/$$i.plx failed verification ***" ; \
-		fi ; \
+		./validate $$i ; \
+		if [ $$? -ne 0 ] ; then \
+			echo "*** Validation of $$i failed ***" >> $(LOG); \
+            test_failed=1 ; \
+        else \
+			./check $$i >> $(LOG) ; \
+			if [ $$? -ne 0 ] ; then \
+				test_failed=1 ; \
+				echo "*** output/$$i.plx failed verification ***" ; \
+			fi ; \
+        fi ; \
 	done ; \
-	if [ $$test_failed -ne 0 ] ; then echo 'Test(s) failed.' ; exit 1 ; fi 
-	@ echo Finished.
+	if [ $$test_failed -ne 0 ] ; then \
+		echo "Test(s) failed. See $(LOG) for details." ; \
+		exit 1 ; \
+	fi 
+	@ echo All files verified.
 
 # For developers: Check the current output against the benchmarks.
 checkall:
