Convert shell scripts to use portable Bourne shell syntax; fix up problems identified by shellcheck
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-x@5211 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/schema/rncfix b/schema/rncfix
--- a/schema/rncfix
+++ b/schema/rncfix
@@ -1,4 +1,4 @@
-#! /usr/bin/env bash
+#! /bin/sh
 #------------------------------------------------------------------------------
 # rncfix
 # 
@@ -29,7 +29,6 @@ parse()
 	case $1 in
 	    -h | --help)
 		usage_msg
-		help_opt=1
 		exit 0
 		;;
 
@@ -42,11 +41,11 @@ parse()
 		exit 1
 		;;
 
-	    [^-]*)
-                if [ "${parsed_arg_count}" -eq 0 ]; then
-		    infile="${1}"
-		elif [ "${parsed_arg_count}" -eq 1 ]; then
-		    outfile="${1}"
+	    [!-]*)
+                if [ "$parsed_arg_count" -eq 0 ]; then
+		    infile="$1"
+		elif [ "$parsed_arg_count" -eq 1 ]; then
+		    outfile="$1"
 		else
 		    echo "Too many arguments!"
 		    exit 1
@@ -64,29 +63,29 @@ parse()
 
 # Parse the command line.
 
-parse $*
+parse "$@"
 
 # Do some error checking.
 
-if [ -z "${infile}" ]; then
+if [ -z "$infile" ]; then
     echo "You must specify an input file!"
     usage_msg
     exit 1
 fi
 
-if [ -z "${outfile}" ]; then
+if [ -z "$outfile" ]; then
     echo "You must specify an output file!"
     usage_msg
     exit 1
 fi
 
-if ! [ -f "${infile}" ]; then
-    echo "Cannot read input file ${infile}"
+if ! [ -f "$infile" ]; then
+    echo "Cannot read input file $infile"
     usage_msg
     exit 1
 fi
 
-if [ -f "${outfile}" ] && [ -z "${force_opt}" ]; then
+if [ -f "$outfile" ] && [ -z "$force_opt" ]; then
     echo "Output file ${outfile} already exists."
     echo "Use -f to force an overwrite."
     exit 1
@@ -98,7 +97,7 @@ fi
 
 # Add the xsi namespace to the beginning of the schema.
 
-cat > ${outfile} <<EOF
+cat > "$outfile" <<EOF
 namespace xsi = "http://www.w3.org/2001/XMLSchema-instance"
 EOF
 
@@ -112,11 +111,11 @@ EOF
 #     | element PlexilPlan { PlexilPlanAttributes?, * })
 #
 
-sed -e 's:\(element[[:space:]]*PlexilPlan[[:space:]]*{[[:space:]]*\)\(.*\)\(}.*\):\1 PlexilPlanAttributes?, \2\3:' ${infile} >> ${outfile}
+sed -e 's:\(element[[:space:]]*PlexilPlan[[:space:]]*{[[:space:]]*\)\(.*\)\(}.*\):\1 PlexilPlanAttributes?, \2\3:' "$infile" >> "$outfile"
 
 # Append the PlexilPlanAttributes pattern to the end of the schema.
 
-cat >> ${outfile} <<EOF
+cat >> "$outfile" <<EOF
 PlexilPlanAttributes = 
   notAllowed
   | attribute xsi:* { xsd:anyURI }*
diff --git a/schema/test/check-plexil-1-2-translation b/schema/test/check-plexil-1-2-translation
--- a/schema/test/check-plexil-1-2-translation
+++ b/schema/test/check-plexil-1-2-translation
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2016, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -39,52 +39,51 @@ then
     exit 1
 fi
 
-outdir="${PLEXIL_HOME}/schema/test/output"
+outdir="$PLEXIL_HOME"/schema/test/output
 
-mkdir -p "${outdir}"
+mkdir -p "$outdir"
 
-px1file="${outdir}/`basename -s .plx $1`.px1"
-px2file="${outdir}/`basename -s .plx $1`.px2"
-rm -f "${px2file}" "${px1file}"
-${PLEXIL_HOME}/schema/test/saxon "${PLEXIL_HOME}/schema/plexil-v1-to-v2.xsl" "$1" "${px2file}"
-if [ $? -ne 0 ]
+px1file="$outdir"/"$(basename "$1" .plx)".px1
+px2file="$outdir"/"$(basename "$1" .plx)".px2
+rm -f "$px2file" "$px1file"
+
+if ! "$PLEXIL_HOME"/schema/test/saxon "$PLEXIL_HOME"/schema/plexil-v1-to-v2.xsl "$1" "$px2file"
 then
-    echo '***' Translation error converting `basename "$1"` to `basename "${px2file}"` '***'
-    echo
-    exit 1
-fi
-xmllint --noout --schema "${PLEXIL_HOME}/schema/core-plexil-v2.xsd" "${px2file}"
-if [ $? -ne 0 ]
-then
-    echo '***' `basename "${px2file}"` fails to validate '***'
+    echo "*** Translation error converting $(basename "$1") to $(basename "$px2file") ***"
     echo
     exit 1
 fi
 
-${PLEXIL_HOME}/schema/test/saxon "${PLEXIL_HOME}/schema/plexil-v2-to-v1.xsl" "${px2file}" "${px1file}"
-if [ $? -ne 0 ]
+if ! xmllint --noout --schema "$PLEXIL_HOME"/schema/core-plexil-v2.xsd "$px2file"
 then
-    echo '***' Translation error converting `basename "$1"` to `basename "${px2file}"` '***'
-    echo
-    exit 1
-fi
-xmllint --noout --schema "${PLEXIL_HOME}/schema/core-plexil.xsd" "${px1file}"
-if [ $? -ne 0 ]
-then
-    echo '***' `basename "${px1file}"` fails to validate '***'
+    echo "*** $(basename "$px2file") fails to validate ***"
     echo
     exit 1
 fi
 
-canonical_before="${outdir}/`basename -s .plx $1`.canonical.plx"
-canonical_after="${outdir}/`basename -s .plx $1`.canonical.px1"
-
-${PLEXIL_HOME}/schema/test/canonicalize "$1" "${canonical_before}"
-${PLEXIL_HOME}/schema/test/canonicalize "${px1file}" "${canonical_after}"
-diff "${canonical_before}" "${canonical_after}"
-if [ $? = 1 ]
+if ! "$PLEXIL_HOME"/schema/test/saxon "$PLEXIL_HOME"/schema/plexil-v2-to-v1.xsl "$px2file" "$px1file"
 then
-    echo '***' Files `basename "${canonical_before}"` and `basename "${canonical_after}"` differ '***'
+    echo "*** Translation error converting $(basename "$px2file") to $(basename "$px1file") ***"
+    echo
+    exit 1
+fi
+
+if ! xmllint --noout --schema "$PLEXIL_HOME"/schema/core-plexil.xsd "$px1file"
+then
+    echo "*** $(basename "$px1file") fails to validate ***"
+    echo
+    exit 1
+fi
+
+canonical_before="$outdir"/"$(basename -s .plx "$1")".canonical.plx
+canonical_after="$outdir"/"$(basename -s .plx "$1")".canonical.px1
+
+"$PLEXIL_HOME"/schema/test/canonicalize "$1" "$canonical_before"
+"$PLEXIL_HOME"/schema/test/canonicalize "$px1file" "$canonical_after"
+
+if ! diff "$canonical_before" "$canonical_after"
+then
+    echo "*** Files $(basename "$canonical_before") and $(basename "$canonical_after") differ ***"
     echo
     exit 1
 fi
