Clean up checkPlexil script
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@5366 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/checkPlexil b/scripts/checkPlexil
--- a/scripts/checkPlexil
+++ b/scripts/checkPlexil
@@ -42,13 +42,14 @@ usage()
 # Check for -d (debug) option
 if [ '-d' = "$1" ]
 then
+    debug="$1"
     shift
 fi
 
 # Check that a file name is provided
 if [ -z "$1" ]
 then
-    echo "Error: no file name supplied"
+    echo "Error: no file name supplied" >&2
     usage
     exit 2
 fi
@@ -56,53 +57,63 @@ fi
 # Make sure a true input file is added as argument
 if [ ! -f "$1" ]
 then
-    echo "Error: Cannot find file $1"
-    exit 2
-fi
-
-if [ -z "$(command -v xmllint)" ]
-then
-    echo "Error: program 'xmllint' not found."
-    echo 'Ensure that it can be found in PATH.'
+    echo "Error: Cannot find file $1" >&2
     exit 2
 fi
 
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo 'Error: Please set environment variable PLEXIL_HOME'
-    echo "to the full pathname of your 'plexil' or 'trunk' directory."
-    echo 'Exiting.'
+    echo 'Error: Please set environment variable PLEXIL_HOME' >&2
+    echo "to the full pathname of your 'plexil' or 'trunk' directory." >&2
+    echo 'Exiting.' >&2
     exit 2
 fi
 
-JAVA=java
 if [ -n "$JAVA_HOME" ]
 then
     JAVA="$JAVA_HOME"/bin/java
+    if [ ! -e "$JAVA" ]
+    then
+        echo "Error: no Java runtime found at $JAVA_HOME" >&2
+        echo 'Please set JAVA_HOME to an existing Java runtime,' >&2
+        echo 'or install a Java runtime environment.' >&2
+        exit 2
+    fi
+else
+    JAVA="$(command -v java)"
+    if [ -z "$JAVA" ]
+    then
+        echo "Error: no Java runtime in path $PATH" >&2
+        echo 'Either set PATH to include a Java runtime,' >&2
+        echo 'set JAVA_HOME to a Java runtime,' >&2
+        echo 'or install a Java runtime environment.' >&2
+        exit 2
+    fi
 fi
 
 # Make sure checker jar file exists
 prog="$PLEXIL_HOME"/checker/global-decl-checker.jar
 if [ ! -f "$prog" ]
 then
-  echo "Cannot find file $prog. To build it:"
-  echo "  cd $PLEXIL_HOME/checker"
-  echo '  ant jar'
-  echo 'If JAR is located elsewhere, please update the location in the script.'
+  echo "Cannot find file $prog. To build it:" >&2
+  echo "  cd $PLEXIL_HOME/checker" >&2
+  echo '  ant jar' >&2
+  echo 'If JAR is located elsewhere, please update the location in the script.' >&2
   exit 2
 fi
 
 # First validate against Core Plexil schema
-xmllint --noout --schema "$PLEXIL_HOME"/schema/core-plexil.xsd "$1"
-result=$?
-if [ $result -ne 0 ]
+if [ -z "$(command -v xmllint)" ]
 then
-    echo "Validation of $1 against PLEXIL schema failed."
+    echo "Warning: program 'xmllint' not found. Skipping validation against schema." >&2
+elif ! xmllint --noout --schema "$PLEXIL_HOME"/schema/core-plexil.xsd "$1"
+then
+    echo "Validation of $1 against PLEXIL schema failed." >&2
     exit 1
 fi
 
 # Run and check result of the program
-"$JAVA" -jar "$prog" "$@"
+"$JAVA" -jar "$prog" "$debug" "$1"
 result=$?
 if [ $result -eq 0 ]
 then
