Update scripts directory with changes from plexil-4
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-x@5132 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/checkPlexil b/scripts/checkPlexil
--- a/scripts/checkPlexil
+++ b/scripts/checkPlexil
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -34,6 +34,39 @@
 #   1 Checking Error(s) Found
 #   2 Unhandled Exception
 
+usage()
+{
+    echo "Usage: `basename $0` [-d] file.plx"
+}
+
+# Check for -d (debug) option
+if [ '-d' = "$1" ]
+then
+    shift
+fi
+
+# Check that a file name is provided
+if [ ! $1 ]
+then
+    echo "Error: no file name supplied"
+    usage
+    exit 2
+fi
+
+# Make sure a true input file is added as argument
+if [ ! -f $1 ]
+then
+    echo "Error: Cannot find file" $1
+    exit 2
+fi
+
+if [ -z `which xmllint` ]
+then
+    echo "Error: program 'xmllint' not found."
+    echo "Ensure that it can be found in PATH."
+    exit 2
+fi
+
 if [ -z "$PLEXIL_HOME" ]
 then
     echo Error: Please set environment variable PLEXIL_HOME
@@ -50,32 +83,13 @@ then
     JAVA=$JAVA_HOME/bin/java
 fi
 
-# Make sure jar file exists
+# Make sure checker jar file exists
 if [ ! -f "${prog}" ]
 then
   echo "Cannot find file ${prog}. To build it:"
   echo "  cd ${PLEXIL_HOME}/checker"
   echo "  ant jar"
   echo "If JAR is located elsewhere, please update the location in the script."
-  exit 2
-fi
-
-if [ '-d' = "$1" ]
-  then
-    shift
-fi
-
- #Make sure a true input file is added as argument
-if [ ! -f $1 ]
-then
-  echo "Cannot find file" $1
-  exit 2
-fi
-
-# No input file selected, exit
-if [ ! $1 ]
-then
-  echo "Usage: checkDecls [-d] file.plx"
   exit 2
 fi
 
diff --git a/scripts/list_ports_in_use b/scripts/list_ports_in_use
--- a/scripts/list_ports_in_use
+++ b/scripts/list_ports_in_use
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -26,7 +26,7 @@
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 osname=`uname`
-if [ "Darwin" = "$osname" ]
+if [ 'Darwin' = "$osname" ]
 then
     # FIXME: sensitive to changes in output format
     netstat -anfinet | grep '^\(tc\|ud\)p' \
@@ -35,13 +35,26 @@ then
     netstat -anfinet6 | grep '^\(tc\|ud\)p' \
         | sed -E -e 's/^(tc|ud)p[46]+ +[0-9]+ + [0-9]+ +[0-9A-Fa-flo%\:\*]+\.([0-9]+) +[0-9A-Fa-f\:\*].*$/\2/g' \
         | grep -v '\*\.\*'
-elif [ "Linux" = "$osname" ]
+elif [ 'Linux' = "$osname" ]
 then
-    netstat -anAinet | grep '^\(tc\|ud\)p' \
-        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
-    netstat -anAinet6 | grep '^\(tc\|ud\)p6' \
-        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9\:].*$/\1/g'
-elif [ "FreeBSD" = "$osname" ]
+    # Prefer ss over deprecated netstat
+    if [ -n 'which ss' ]
+    then
+	ss -an4 | grep '^\(tc\|ud\)p' \
+            | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
+	ss -an6 | tail -n +2 \
+            | sed -e 's/^.*\:\([0-9]\+\) \+.*$/\1/g'
+    elif [ -n 'which netstat' ]
+    then
+	netstat -anAinet | grep '^\(tc\|ud\)p' \
+            | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
+	netstat -anAinet6 | grep '^\(tc\|ud\)p6' \
+            | sed -e 's/^.*\:\([0-9]\+\) \+[0-9\:].*$/\1/g'
+    else
+	echo "Error: neither 'ss' nor 'netstat' available" >2
+	exit 1
+    fi
+elif [ 'FreeBSD' = "$osname" ]
 then
     netstat -anfinet | grep '^\(tc\|ud\)p4' \
         | sed -E -e 's/^...4 +[0-9]+ +[0-9]+ (\*|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+) .*$/\2/g' \
diff --git a/scripts/make-tarball b/scripts/make-tarball
--- a/scripts/make-tarball
+++ b/scripts/make-tarball
@@ -1,6 +1,6 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-# Copyright (c) 2006-2016, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -33,6 +33,7 @@ set -e
 usage()
 {
     echo "usage: $0 release-id [svn-rev]"
+    echo "Best to run this in an empty temporary directory"
 }
 
 if [ -z "$1" ]
@@ -49,12 +50,31 @@ then
     rev=$2
 fi
 
-echo "Checking out revision $rev into temporary directory $relid"
+set -e # exit on error
+
 svn export -r $rev https://svn.code.sf.net/p/plexil/code/branches/plexil-x "$relid"
 
 echo "Installing autotools files and building configure script"
 cd "$relid"
 PLEXIL_HOME="$PWD" make src/configure
+
+# Prebuild expression parser core
+# NOTE: this must track the contents of src/xml-parser/Makefile.am
+gperf -m 8 --output-file=src/xml-parser/ExpressionMap.hh src/xml-parser/ExpressionMap.gperf
+
+# Build Java apps users will need (and clean up build leftovers)
+make plexil-compiler
+rm -rf compilers/plexil/classes compilers/plexil/generated
+
+make plexilscript
+rm -rf compilers/plexilscript/classes compilers/plexilscript/generated
+
+make pv
+rm -rf viewers/pv/build
+
+make checker
+rm -rf checker/build
+
 cd ..
 
 echo "Generating tar file ${relid}.tar.gz"
diff --git a/scripts/plexilc b/scripts/plexilc
--- a/scripts/plexilc
+++ b/scripts/plexilc
@@ -1,6 +1,7 @@
-#!/usr/bin/env bash
+#!/bin/sh
+# Generalized compiler driver for Plexil source files
 
-# Copyright (c) 2006-2016, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -31,7 +32,8 @@
 #
 #  The type of source file given is partly identified by its extension:
 #
-#    Plexil plans                 : .ple, .epx
+#    Standard Plexil plans        : .plp, .ple
+#    Extended Plexil (XML) plans  : .epx
 #    Plexilisp plans and scripts  : .pli
 #    Plexil simulator scripts     : .pst
 #
@@ -41,83 +43,221 @@
 #    Plexil scripts (XML)         : .psx
 #
 
-function usage ()
+usage ()
 {
     echo "Usage: $0 [options] <source-file>"
-    echo "Options are"
-    echo "  -c, -check              Run static checker on output (only valid for plan files)"
-    echo "  -d, -debug <logfile>    Print debug information to <logfile>"
-    echo "  -h, -help               Print this help and exit"
-    echo "  -o, -output <outfile>   Write translator output to <outfile>"
-    echo "  -q, -quiet              Parse files quietly"
+    echo " Compile a Plexil plan or simulator script to XML"
+    echo "Options:"
+    echo "  -h, -help, --help       Print this help and exit"
     echo "  -v, -version            Print translator version and exit"
-    echo "Some options are not supported for all file formats."
+    echo "  -c, -check              Run static checker on output"
+    echo "                          (plan files only)"
+    echo "  -d, -debug              Print debug information to stderr"
+    echo "                          (.plp, .ple files only)"
+    echo "  -o, -output <outfile>   Write translator output to <outfile>"
+    echo "                          (ignored for .pli files)"
+    echo "  -q, -quiet              Parse files quietly"
+    echo "  -I <directory>          Include directory"
+    echo "                          (.plp files only)"
+    echo "Not all options are supported for all file formats."
+    echo
+    echo "Recognized extensions are:"
+    echo "  .epx - Extended Plexil XML plan"
+    echo "  .ple - Plexil plan"
+    echo "  .plp - Plexil plan with preprocessing"
+    echo "  .pli - Plexilisp plan or simulation script"
+    echo "  .pst - Plexilscript simulation script"
 }
 
-# Check environment variables
-if [ -z "$PLEXIL_HOME" ]
-then
-    echo Error: Please set environment variable PLEXIL_HOME
-    echo to the full pathname of your 'plexil' or 'trunk' directory.
-    exit 1
-fi
+check_env()
+{
+    if [ -z "$PLEXIL_HOME" ]
+    then
+        echo Error: Please set environment variable PLEXIL_HOME
+        echo to the full pathname of your 'plexil' or 'trunk' directory.
+        exit 1
+    fi
+    . ${PLEXIL_HOME}/scripts/plexil-setup.sh
+}
 
-. ${PLEXIL_HOME}/scripts/plexil-setup.sh
+generate_output_fname()
+{
+    if [ -n "$output" ]
+    then
+        echo $output
+        return
+    fi
 
-JARS_DIR=${PLEXIL_HOME}/jars
-ANTLR_RUNTIME_JAR=antlr-3.5.2-complete-no-st3.jar
-JAVA=java
-if [ -n "$JAVA_HOME" ]
-then
-    JAVA=$JAVA_HOME/bin/java
-fi
+    in_ext=`expr $1 : '.*\.\([a-z][a-z][a-z]\)$'`
+    case "$in_ext" in
+        ( ple | pli | plp | epx )
+        echo $1 | sed -e "s/$in_ext$/plx/"
+        ;;
 
-# Commands to execute
-plexil_compiler="$JAVA -classpath $JARS_DIR/PlexilCompiler.jar:$JARS_DIR/$ANTLR_RUNTIME_JAR:$JARS_DIR/nanoxml.jar:$JARS_DIR/saxon.jar plexil.Compiler"
-plexilscript_compiler="$JAVA -cp ${JARS_DIR}/plexilscript.jar:${JARS_DIR}/antlr.jar plexilscript.PlexilScriptParse"
-plexil_checker="$PLEXIL_HOME/scripts/checkDecls"
+        pst )
+            echo $1 | sed -e "s/$in_ext$/psx/"
+            ;;
+        * )
+            echo Unrecognized filename extension "$in_ext" for "$1" >&2
+            echo Supported extensions are: epx ple pli pst >&2
+            exit 1
+            ;;
+    esac
+}
+
+compile_std_plexil()
+{
+    # Plexil plan
+    options=""
+    if [ -n "$debug" ]
+    then
+        options="$options --debug" 
+    fi
+
+    output=`generate_output_fname $1`
+
+    if [ -n "$quiet" ]
+    then
+        $plexil_compiler $options -o $output $1 > /dev/null 2>&1
+    else 
+        $plexil_compiler $options -o $output $1
+    fi
+    status=$?
+    if [ $status -ne 0 ]
+    then
+        echo Error: Standard Plexil compilation of $1 failed.
+        exit $status
+    fi
+
+    if [ -n "$check" ]
+    then
+        $plexil_checker $output
+    fi
+}
+
+compile_plexilisp()
+{
+    # Plexilisp plan/script
+    if [ -n "$quiet" ]
+    then
+        emacs --batch --no-site-file --load $PLEXIL_HOME/compilers/plexilisp/plexil.el $1 --eval '(plexil)' > /dev/null 2>&1
+    else
+        emacs --batch --no-site-file --load $PLEXIL_HOME/compilers/plexilisp/plexil.el $1 --eval '(plexil)'
+    fi
+
+    if [ -n "$output" ]
+    then
+        echo "Warning: -o/-output option is ignored for Plexilisp"
+        output=""
+    fi
+
+    # If plexilisp generates a plan, we can check it.
+    output=`generate_output_fname $1`
+    if [ -r $output -a -n "$check" ]
+    then
+        $plexil_checker $output
+    fi
+}
+
+compile_ext_plexil()
+{
+    # Extended Plexil XML plan
+    output=`generate_output_fname $1`
+    $PLEXIL_HOME/scripts/eplexil $1 $output
+    status=$?
+    if [ $status -ne 0 ]
+    then
+        echo Error: Extended Plexil translation of $1 failed.
+        exit $status
+    fi
+
+    if [ -n "$check" ]
+    then
+        $plexil_checker $output
+    fi
+}
+
+compile_plexilscript()
+{
+    # Plexilscript
+    output=`generate_output_fname $1`
+    $plexilscript_compiler < $1 > $output
+    status=$?
+    if [ $status -ne 0 ]
+    then
+        echo Error: compilation of $1 failed.
+        exit $status
+    fi
+}
+
+compile_plp()
+{
+    # Standard Plexil w/ preprocessing
+    ple_fname=`echo "$1" | sed -e 's|.plp$|.ple|'`
+    ${PLEXIL_HOME}/scripts/plexilpp $pp_args -o "$ple_fname" "$1"
+    status=$?
+    if [ $status -ne 0 ]
+    then
+        echo Error: Preprocessing of $1 failed.
+        exit $status
+    fi
+
+    compile_std_plexil "$ple_fname"
+    # TODO: delete ple_fname??
+}
 
 # Parse options
-while [ "${1:0:1}" = '-' ]
+while ( echo "$1" | grep -q -e '^-.*' )
 do
-    if [ "$1" = '-c' -o "$1" = '-check' ]
-    then
-	check=$1
-	shift
-    elif [ "$1" = '-d' -o "$1" = '-debug' ]
-    then
-	if [ -z "$2" -o "${2:0:1}" = '-' ]
-	then
-	    echo "Error: debug filename missing for $1 option"
-	    usage
-	    exit 1
-	fi
-	debug=$2
-	shift 2
-    elif [ "$1" = '-h' -o "$1" = '-help' ]
-    then
-	usage
-	exit 0
-    elif [ "$1" = '-o' -o "$1" = '-output' ]
-    then
-	if [ -z "$2" -o "${2:0:1}" = '-' ]
-	then
-	    echo "Error: output filename missing for $1 option"
-	    usage
-	    exit 1
-	fi
-	output=$2
-	shift 2
-    elif [ "$1" = '-q' -o "$1" = '-quiet' ]
-    then
-	quiet=$1
-	shift
-    elif [ "$1" = '-v' -o "$1" = '-version' ]
-    then
-	echo 'plexilc script version 1.0'
-	$plexil_compiler --version
-	exit 0
-    fi
+    case "$1" in
+        ( -c | -check )
+        check=$1
+        shift
+        ;;
+
+        ( -d | -debug )
+        debug=$1
+        shift
+        ;;
+
+        ( -h | -help | --help )
+        usage
+        exit 0
+        ;;
+
+        -I )
+            pp_args="$pp_args $1 $2"
+            shift 2
+            ;;
+        
+        ( -o | -output )
+        if [ -z "$2" ] || ( echo "$2" | grep -q -e '^-.*' )
+        then
+            echo "Error: output filename missing for $1 option"
+            usage
+            exit 1
+        fi
+        output=$2
+        shift 2
+        ;;
+
+        ( -q | -quiet )
+        quiet=$1
+        shift
+        ;;
+
+        ( -v | -version )
+        echo 'plexilc script version 1.2'
+        $plexil_compiler --version
+        exit 0
+        ;;
+
+        *)
+            echo "$0: Unrecognized option $1" >&2
+            usage
+            exit 1
+            ;;
+    esac
 done
 
 # If we got this far, we are expecting a filename to translate
@@ -134,90 +274,50 @@ then
     exit 1
 fi
 
-# Select translator for this file
-if [ `expr $1 : '.*\.ple\$'` -ne 0 ]
+check_env
+
+JARS_DIR=${PLEXIL_HOME}/jars
+ANTLR_RUNTIME_JAR=antlr-3.5.2-complete-no-st3.jar
+JAVA=java
+if [ -n "$JAVA_HOME" ]
 then
-	# Plexil plan
-    options=""
-    if [ -n "$debug" ]
-    then
-	options="$options -d $debug" 
-    fi
-    if [ -n "$quiet" ]
-    then
-	options="$options -q"
-    fi
-
-    if [ -z "$output" ]
-    then
-	output=${1//\.ple/.plx}
-    fi
-
-    $plexil_compiler $options -o $output $1
-    status=$?
-    if [ $status -ne 0 ]
-    then
-	echo Error: compilation of $1 failed.
-	exit $status
-    fi
-
-    if [ -n "$check" ]
-    then
-	$plexil_checker $output
-    fi
-
-elif [ `expr $1 : '.*\.pli\$'` -ne 0 ]
-then
-	# Plexilisp plan/script
-
-    if [ -n "$quiet" ]
-    then
-	emacs --batch --no-site-file --load $PLEXIL_HOME/compilers/plexilisp/plexil.el $1 --eval '(plexil)' > /dev/null 2>&1
-    else
-	emacs --batch --no-site-file --load $PLEXIL_HOME/compilers/plexilisp/plexil.el $1 --eval '(plexil)'
-    fi
-
-	# If plexilisp generates a plan, we can check it.
-    output=${1//\.pli/.plx}
-    if [ -r $output -a -n "$check" ]
-    then
-	$plexil_checker $output
-    fi
-
-elif [ `expr $1 : '.*\.epx\$'` -ne 0 ]
-then
-	# Extended Plexil XML plan
-
-    output=${1//\.epx/.plx}
-    $PLEXIL_HOME/scripts/eplexil $1 $output
-
-    if [ -n "$check" ]
-    then
-	$plexil_checker $output
-    fi
-
-elif [ `expr $1 : '.*\.pst\$'` -ne 0 ]
-then
-	# Plexilscript
-    if [ -z "$output" ]
-    then
-	output=${1//\.pst/.psx}
-    fi
-    $plexilscript_compiler < $1 > $output
-    status=$?
-    if [ $status -ne 0 ]
-    then
-	echo Error: compilation of $1 failed.
-	exit $status
-    fi
-else
-    echo "Error: file $1 not recognized."
-    echo "Recognized extensions are:"
-    echo "  .epx - Extended Plexil XML plan"
-    echo "  .ple - Plexil plan"
-    echo "  .pli - Plexilisp plan or simulation script"
-    echo "  .pst - Plexilscript simulation script"
-    exit 1
+    JAVA=$JAVA_HOME/bin/java
 fi
+
+# Commands to execute
+plexil_compiler="$JAVA -classpath $JARS_DIR/PlexilCompiler.jar:$JARS_DIR/$ANTLR_RUNTIME_JAR:$JARS_DIR/nanoxml.jar:$JARS_DIR/saxon.jar plexil.Compiler"
+plexilscript_compiler="$JAVA -cp ${JARS_DIR}/plexilscript.jar:${JARS_DIR}/antlr.jar plexilscript.PlexilScriptParse"
+plexil_checker="$PLEXIL_HOME/scripts/checkDecls"
+
+# Select translator for this file based on extension
+in_ext=`expr $1 : '.*\.\([a-z][a-z][a-z]\)$'`
+
+case $in_ext in
+    epx )
+        compile_ext_plexil $1
+        ;;
+    
+    ple )
+        compile_std_plexil $1
+        ;;
+    
+    plp )
+        compile_plp $1
+        ;;
+    
+    pli )
+        compile_plexilisp $1
+        ;;
+
+    pst )
+        compile_plexilscript $1
+        ;;
+
+    * )
+        echo Unable to select compiler for "$1"
+        usage
+        exit 1
+        ;;
+esac
 
 exit 0
