Fix a variety of minor and major problems in the scripts directory
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-3@3081 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/checkDecls b/scripts/checkDecls
--- a/scripts/checkDecls
+++ b/scripts/checkDecls
@@ -34,15 +34,24 @@
 #   1 Checking Error(s) Found
 #   2 Unhandled Exception
 
+if [ -z "$PLEXIL_HOME" ]
+then
+    echo Error: Please set environment variable PLEXIL_HOME
+    echo to the full pathname of your 'plexil' or 'trunk' directory.
+    echo Exiting.
+    exit 2
+fi
+
 prog=${PLEXIL_HOME}/checker/global-decl-checker.jar
 args=$*
 
 # Make sure jar file exists
 if [ ! -f "${prog}" ]
 then
-  echo "Cannot find file ${prog}. Please run:"
+  echo "Cannot find file ${prog}. To build it:"
+  echo "  cd ${PLEXIL_HOME}/checker"
   echo "  ant jar"
-  echo "If JAR is located elsewhere, please update the location in the script"
+  echo "If JAR is located elsewhere, please update the location in the script."
   exit 2
 fi
 
