Fix some issues with plexil-4 merge in plexilc; add .plp as fully supported extension
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-6@5355 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/list_ports_in_use b/scripts/list_ports_in_use
--- a/scripts/list_ports_in_use
+++ b/scripts/list_ports_in_use
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -25,7 +25,9 @@
 # TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-osname=`uname`
+set -e
+
+osname="$(uname)"
 if [ 'Darwin' = "$osname" ]
 then
     # FIXME: sensitive to changes in output format
@@ -38,30 +40,30 @@ then
 elif [ 'Linux' = "$osname" ]
 then
     # Prefer ss over deprecated netstat
-    if [ -n 'which ss' ]
+    if [ -n "$(command -v ss)" ]
     then
-	ss -an4 | grep '^\(tc\|ud\)p' \
+        ss -an4 | grep '^\(tc\|ud\)p' \
             | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
-	ss -an6 | tail -n +2 \
+        ss -an6 | tail -n +2 \
             | sed -e 's/^.*\:\([0-9]\+\) \+.*$/\1/g'
-    elif [ -n 'which netstat' ]
+    elif [ -n "$(command -v netstat)" ]
     then
-	netstat -anAinet | grep '^\(tc\|ud\)p' \
+        netstat -anAinet | grep '^\(tc\|ud\)p' \
             | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
-	netstat -anAinet6 | grep '^\(tc\|ud\)p6' \
+        netstat -anAinet6 | grep '^\(tc\|ud\)p6' \
             | sed -e 's/^.*\:\([0-9]\+\) \+[0-9\:].*$/\1/g'
     else
-	echo "Error: neither 'ss' nor 'netstat' available" >2
-	exit 1
+        echo "Error: neither 'ss' nor 'netstat' available" >&2
+        exit 1
     fi
 elif [ 'FreeBSD' = "$osname" ]
 then
     netstat -anfinet | grep '^\(tc\|ud\)p4' \
         | sed -E -e 's/^...4 +[0-9]+ +[0-9]+ (\*|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+) .*$/\2/g' \
-	| grep -v '\*\.\*'
+        | grep -v '\*\.\*'
     netstat -anfinet6 | grep '^\(tc\|ud\)p6' \
         | sed -E -e 's/^...6 +[0-9]+ +[0-9]+ [0-9a-floA-F:%\*]+\.([0-9]+).*$/\1/g' \
-	| grep -v '\*\.\*'
+        | grep -v '\*\.\*'
 else
     echo "Error: Don't know how to get active port list on $osname"
     exit 1
diff --git a/scripts/plexilc b/scripts/plexilc
--- a/scripts/plexilc
+++ b/scripts/plexilc
@@ -46,27 +46,27 @@
 usage ()
 {
     echo "Usage: $0 [options] <source-file>"
-    echo " Compile a Plexil plan or simulator script to XML"
-    echo "Options:"
-    echo "  -h, -help, --help       Print this help and exit"
-    echo "  -v, -version            Print translator version and exit"
-    echo "  -c, -check              Run static checker on output"
-    echo "                          (plan files only)"
-    echo "  -d, -debug              Print debug information to stderr"
-    echo "                          (.plp, .ple files only)"
-    echo "  -o, -output <outfile>   Write translator output to <outfile>"
-    echo "                          (ignored for .pli files)"
-    echo "  -q, -quiet              Parse files quietly"
-    echo "  -I <directory>          Include directory"
-    echo "                          (.plp files only)"
-    echo "Not all options are supported for all file formats."
+    echo ' Compile a Plexil plan or simulator script to XML'
+    echo 'Options:'
+    echo '  -h, -help, --help       Print this help and exit'
+    echo '  -v, -version            Print translator version and exit'
+    echo '  -c, -check              Run static checker on output'
+    echo '                          (plan files only)'
+    echo '  -d, -debug              Print debug information to stderr'
+    echo '                          (.plp, .ple files only)'
+    echo '  -o, -output <outfile>   Write translator output to <outfile>'
+    echo '                          (ignored for .pli files)'
+    echo '  -q, -quiet              Parse files quietly'
+    echo '  -I <directory>          Include directory'
+    echo '                          (.plp files only)'
+    echo 'Not all options are supported for all file formats.'
     echo
-    echo "Recognized extensions are:"
-    echo "  .epx - Extended Plexil XML plan"
-    echo "  .ple - Plexil plan"
-    echo "  .plp - Plexil plan with preprocessing"
-    echo "  .pli - Plexilisp plan or simulation script"
-    echo "  .pst - Plexilscript simulation script"
+    echo 'Recognized extensions are:'
+    echo '  .epx - Extended Plexil XML plan'
+    echo '  .ple - Plexil plan'
+    echo '  .plp - Plexil plan with preprocessing'
+    echo '  .pli - Plexilisp plan or simulation script'
+    echo '  .pst - Plexilscript simulation script'
 }
 
 check_env()
@@ -78,18 +78,18 @@ check_env()
         exit 1
     fi
     # shellcheck source=plexil-setup.sh
-    . "${PLEXIL_HOME}/scripts/plexil-setup.sh"
+    . "$PLEXIL_HOME"/scripts/plexil-setup.sh
 }
 
 generate_output_fname()
 {
     if [ -n "$output" ]
     then
-        echo "$output"
+        printf '%s\n' "$output"
         return
     fi
 
-    in_ext=$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')
+    in_ext="$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')"
     case "$in_ext" in
         ( ple | pli | plp | epx )
         echo "$1" | sed -e "s/$in_ext$/plx/"
@@ -99,11 +99,29 @@ generate_output_fname()
             echo "$1" | sed -e "s/$in_ext$/psx/"
             ;;
         * )
-            echo "Unrecognized filename extension $in_ext for $1" >&2
-            echo "Supported extensions are: epx ple pli pst" >&2
+            echo "Unrecognized filename extension \"$in_ext\" for $1" >&2
+            echo 'Supported extensions are: epx ple pli plp pst' >&2
             exit 1
             ;;
     esac
+}
+
+check_env
+
+JARS_DIR="$PLEXIL_HOME"/jars
+ANTLR_RUNTIME_JAR=antlr-3.5.2-complete-no-st3.jar
+JAVA=java
+if [ -n "$JAVA_HOME" ]
+then
+    JAVA="$JAVA_HOME"/bin/java
+fi
+
+# Commands to execute
+plexil_checker="$PLEXIL_HOME/scripts/checkDecls"
+
+std_plexil_compiler()
+{
+    "$JAVA" -classpath "$JARS_DIR/PlexilCompiler.jar:$JARS_DIR/$ANTLR_RUNTIME_JAR:$JARS_DIR/nanoxml.jar:$JARS_DIR/saxon.jar" plexil.Compiler "$@"
 }
 
 compile_std_plexil()
@@ -115,15 +133,15 @@ compile_std_plexil()
         options="$options --debug" 
     fi
 
-    output=$(generate_output_fname "$1")
+    output="$(generate_output_fname "$1")"
 
     if [ -n "$quiet" ]
     then
         # shellcheck disable=SC2086
-        $plexil_compiler $options -o "$output" "$1" > /dev/null 2>&1
+        std_plexil_compiler $options -o "$output" "$1" > /dev/null 2>&1
     else 
         # shellcheck disable=SC2086
-        $plexil_compiler $options -o "$output" "$1"
+        std_plexil_compiler $options -o "$output" "$1"
     fi
     status=$?
     if [ $status -ne 0 ]
@@ -143,19 +161,19 @@ compile_plexilisp()
     # Plexilisp plan/script
     if [ -n "$quiet" ]
     then
-        emacs --batch --no-site-file --load "$PLEXIL_HOME/compilers/plexilisp/plexil.el" "$1" --eval '(plexil)' > /dev/null 2>&1
+        emacs --batch --no-site-file --load "$PLEXIL_HOME"/compilers/plexilisp/plexil.el "$1" --eval '(plexil)' > /dev/null 2>&1
     else
-        emacs --batch --no-site-file --load "$PLEXIL_HOME/compilers/plexilisp/plexil.el" "$1" --eval '(plexil)'
+        emacs --batch --no-site-file --load "$PLEXIL_HOME"/compilers/plexilisp/plexil.el "$1" --eval '(plexil)'
     fi
 
     if [ -n "$output" ]
     then
-        echo "Warning: -o/-output option is ignored for Plexilisp"
+        echo 'Warning: -o/-output option is ignored for Plexilisp'
         output=""
     fi
 
     # If plexilisp generates a plan, we can check it.
-    output=$(generate_output_fname "$1")
+    output="$(generate_output_fname "$1")"
     if [ -r "$output" ] && [ -n "$check" ]
     then
         "$plexil_checker" "$output"
@@ -165,8 +183,8 @@ compile_plexilisp()
 compile_ext_plexil()
 {
     # Extended Plexil XML plan
-    output=$(generate_output_fname "$1")
-    "$PLEXIL_HOME/scripts/eplexil" "$1" "$output"
+    output="$(generate_output_fname "$1")"
+    "$PLEXIL_HOME"/scripts/eplexil "$1" "$output"
     status=$?
     if [ $status -ne 0 ]
     then
@@ -184,7 +202,7 @@ compile_plexilscript()
 {
     # Plexilscript
     output=$(generate_output_fname "$1")
-    $plexilscript_compiler < "$1" > "$output"
+    "$JAVA" -classpath "$JARS_DIR/plexilscript.jar:$JARS_DIR/antlr.jar" plexilscript.PlexilScriptParse < "$1" > "$output"
     status=$?
     if [ $status -ne 0 ]
     then
@@ -196,9 +214,9 @@ compile_plexilscript()
 compile_plp()
 {
     # Standard Plexil w/ preprocessing
-    ple_fname=$(echo "$1" | sed -e 's|.plp$|.ple|')
+    ple_fname="$(echo "$1" | sed -e 's|.plp$|.ple|')"
     # shellcheck disable=SC2086
-    "${PLEXIL_HOME}/scripts/plexilpp" $pp_args -o "$ple_fname" "$1"
+    "$PLEXIL_HOME"/scripts/plexilpp $pp_args -o "$ple_fname" "$1"
     status=$?
     if [ $status -ne 0 ]
     then
@@ -207,7 +225,20 @@ compile_plp()
     fi
 
     compile_std_plexil "$ple_fname"
-    # TODO: delete ple_fname??
+    status=$?
+
+    if [ $status -ne 0 ]
+    then
+        # Don't delete preprocessor output file in case
+        # the error is a result of a macro goof.
+        echo "Error: Compilation of $1 failed." >&2
+        exit $status
+    fi
+
+    # Delete preprocessor output file
+    /bin/rm -f "$ple_fname"
+
+    return 0
 }
 
 # Parse options
@@ -215,12 +246,12 @@ while ( echo "$1" | grep -q -e '^-.*' )
 do
     case "$1" in
         ( -c | -check )
-        check=$1
+        check="$1"
         shift
         ;;
 
         ( -d | -debug )
-        debug=$1
+        debug="$1"
         shift
         ;;
 
@@ -241,18 +272,18 @@ do
             usage
             exit 1
         fi
-        output=$2
+        output="$2"
         shift 2
         ;;
 
         ( -q | -quiet )
-        quiet=$1
+        quiet="$1"
         shift
         ;;
 
         ( -v | -version )
         echo 'plexilc script version 1.2'
-        "$plexil_compiler" --version
+        std_plexil_compiler --version
         exit 0
         ;;
 
@@ -278,25 +309,10 @@ then
     exit 1
 fi
 
-check_env
-
-JARS_DIR="${PLEXIL_HOME}/jars"
-ANTLR_RUNTIME_JAR=antlr-3.5.2-complete-no-st3.jar
-JAVA=java
-if [ -n "$JAVA_HOME" ]
-then
-    JAVA="$JAVA_HOME/bin/java"
-fi
-
-# Commands to execute
-plexil_compiler="$JAVA -classpath $JARS_DIR/PlexilCompiler.jar:$JARS_DIR/$ANTLR_RUNTIME_JAR:$JARS_DIR/nanoxml.jar:$JARS_DIR/saxon.jar plexil.Compiler"
-plexilscript_compiler="$JAVA -cp ${JARS_DIR}/plexilscript.jar:${JARS_DIR}/antlr.jar plexilscript.PlexilScriptParse"
-plexil_checker="$PLEXIL_HOME/scripts/checkDecls"
-
 # Select translator for this file based on extension
-in_ext=$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')
+in_ext="$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')"
 
-case $in_ext in
+case "$in_ext" in
     epx )
         compile_ext_plexil "$1"
         ;;
