Minor cleanups
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@5286 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/make-tarball b/scripts/make-tarball
--- a/scripts/make-tarball
+++ b/scripts/make-tarball
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -33,7 +33,6 @@ usage()
     echo "Best to run this in an empty temporary directory"
 }
 
-
 if [ -z "$1" ]
 then
     usage
@@ -42,24 +41,31 @@ fi
 
 relid=$1
 
-rev=HEAD
+rev='HEAD'
 if [ -n "$2" ]
 then
-    rev=$2
+    rev="$2"
+fi
+
+GPERF="$(which gperf)"
+if [ -z "$GPERF" ]
+then
+    echo "Error: Can't find the 'gperf' program. Exiting."
+    exit 1
 fi
 
 set -e # exit on error
 
-svn export -r $rev https://svn.code.sf.net/p/plexil/code/branches/plexil-4 $relid
-cd $relid
-export PLEXIL_HOME=$PWD
+svn export -r "$rev" https://svn.code.sf.net/p/plexil/code/branches/plexil-4 "$relid" > /dev/null
+cd "$relid"
+export PLEXIL_HOME="$PWD"
 
 # Prebuild 'configure' script
 make src/configure
 
 # Prebuild expression parser core
 # NOTE: this must track the contents of src/xml-parser/Makefile.am
-gperf -m 8 --output-file=src/xml-parser/ExpressionMap.hh src/xml-parser/ExpressionMap.gperf
+"$GPERF" -m 8 --output-file=src/xml-parser/ExpressionMap.hh src/xml-parser/ExpressionMap.gperf
 
 # Build Java apps users will need (and clean up build leftovers)
 make plexil-compiler
@@ -75,7 +81,7 @@ make checker
 rm -rf checker/build
 
 cd ..
-tar czf ${relid}.tar.gz $relid
-rm -rf $relid
+tar cjf "${relid}.tar.bz2" "$relid"
+rm -rf "$relid"
 
 exit 0
