Standard PLEXIL compiler: Try to simplify and optimize the grammar; Java code updates to match

diff --git a/scripts/make-tarball b/scripts/make-tarball
--- a/scripts/make-tarball
+++ b/scripts/make-tarball
@@ -1,6 +1,6 @@
-#! /bin/sh
+#! /bin/sh -e
 
-# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2021, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -25,73 +25,84 @@
 # TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Run this script in an empty temp directory
-
-# Exit on any error
-set -e
-
 usage()
 {
-    echo "usage: $0 release-id [svn-rev]"
-    echo "Best to run this in an empty temporary directory"
+    cat <<EOF
+Usage: $(basename "$0") release-id [tree-ish]
+ Writes a distribution tar file for PLEXIL to
+ <release-id>.tar.bz2 in the working directory.
+
+ [tree-ish] defaults to HEAD.
+ See 'git help' for more information.
+
+*** Must be run from the root directory of a Plexil git clone. ***
+EOF
 }
 
 if [ -z "$1" ]
 then
-    usage
+    usage >&2 
     exit 1
 fi
 
-relid=$1
-
+RELID="$1"
 rev='HEAD'
 if [ -n "$2" ]
 then
     rev="$2"
 fi
 
-GPERF="$(which gperf)"
-if [ -z "$GPERF" ]
-then
-    echo "Error: Can't find the 'gperf' program. Exiting."
-    exit 1
-fi
+# $1 is the name of a command required for the operation
+find_command()
+{
+    CMD="$(command -v "$1")"
+    if [ -z "$CMD" ]
+    then
+        echo "$(basename "$0"): Required program \"$1\" not found in PATH" >&2
+        exit 1
+    fi
+}
 
-set -e # exit on error
+# Commands required for the task which are not installed by default on some platforms
+find_command ant
+find_command autoreconf
+find_command git
+find_command gperf
+find_command javac
 
-svn export -r "$rev" https://svn.code.sf.net/p/plexil/code/branches/plexil-4 "$relid" > /dev/null
-cd "$relid"
-export PLEXIL_HOME="$PWD"
+STARTDIR="$PWD"
 
-echo "Installing autotools files and building configure script"
-cd "$relid"
-PLEXIL_HOME="$PWD" make src/configure
+WORKDIR="$(mktemp -d -t "$RELID")"
+echo "Exporting to temporary directory $WORKDIR"
+git export --format=tar --prefix="$RELID/" "$rev" | ( cd "$WORKDIR" && tar xf - )
+
+cd "${WORKDIR}/$RELID"
+PLEXIL_HOME="$PWD"
+export PLEXIL_HOME
+
+echo 'Installing autotools files and building configure script'
+make src/configure
 
 # Prebuild expression parser core
-# NOTE: this must track the contents of src/xml-parser/Makefile.am
-"$GPERF" -m 8 --output-file=src/xml-parser/ExpressionMap.hh src/xml-parser/ExpressionMap.gperf
+# NOTE: this command line must track what is in src/xml-parser/Makefile.am
+echo 'Generating XML parser perfect hash function'
+gperf -m 8 --output-file=src/xml-parser/ExpressionMap.hh src/xml-parser/ExpressionMap.gperf
 
 # Build Java apps users will need (and clean up build leftovers)
-make plexil-compiler
-rm -rf compilers/plexil/classes compilers/plexil/generated
+echo 'Bulding Java applications'
+( cd compilers/plexil && ant install && ant clean )
+( cd compilers/plexilscript && ant install && ant clean )
+( cd viewers/pv/build && ant jar && ant clean )
+( cd checker && ant jar && ant clean )
 
-make plexilscript
-rm -rf compilers/plexilscript/classes compilers/plexilscript/generated
-
-make pv
-rm -rf viewers/pv/build
-
-make checker
-rm -rf checker/build
+# Do any additional cleanup here
 
 cd ..
-echo "Generating tar file ${relid}.tar.bz2"
-tar cjf "${relid}.tar.bz2" "$relid"
-rm -rf "$relid"
+echo "Writing tar file to ${STARTDIR}/${RELID}.tar.bz2"
+tar cjf "${STARTDIR}/${RELID}.tar.bz2" "$RELID"
 
-echo "Deleting temporary directory $relid"
-rm -rf "$relid"
+cd "$STARTDIR"
+echo "Deleting $WORKDIR"
+rm -rf "$WORKDIR"
 
-echo "Done"
-
-exit 0
+echo 'Done.'
