Prepare for 4.5.0RC1 release
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@5008 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/make-tarball b/scripts/make-tarball
--- a/scripts/make-tarball
+++ b/scripts/make-tarball
@@ -1,6 +1,6 @@
 #! /usr/bin/env bash
 
-# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2018, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -30,6 +30,7 @@
 usage()
 {
     echo "usage: $0 release-id [svn-rev]"
+    echo "Best to run this in an empty temporary directory"
 }
 
 
@@ -47,10 +48,28 @@ then
     rev=$2
 fi
 
+set -e # exit on error
+
 svn export -r $rev https://svn.code.sf.net/p/plexil/code/branches/plexil-4 $relid
 cd $relid
 export PLEXIL_HOME=$PWD
+
+# Prebuild 'configure' script
 make src/configure
+
+# Build Java apps users will need (and clean up build leftovers)
+make plexil-compiler
+rm -rf compilers/plexil/classes compilers/plexil/generated
+
+make plexilscript
+rm -rf compilers/plexilscript/classes compilers/plexilscript/generated
+
+make pv
+rm -rf viewers/pv/build
+
+make checker
+rm -rf checker/build
+
 cd ..
 tar czf ${relid}.tar.gz $relid
 rm -rf $relid
