Clean up and robustify translator scripts plexilc, plexilisp, plexilscript, eplexil
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@5359 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/plexilisp b/scripts/plexilisp
--- a/scripts/plexilisp
+++ b/scripts/plexilisp
@@ -31,10 +31,17 @@
 
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo Error: Please set environment variable PLEXIL_HOME
-    echo to the full pathname of your 'plexil' or 'trunk' directory.
-    echo Exiting.
+    echo 'Error: Please set environment variable PLEXIL_HOME' >&2
+    echo "to the full pathname of your 'plexil' or 'trunk' directory." >&2
+    echo 'Exiting.' >&2
     exit 1
 fi
 
-emacs --batch --no-site-file --load "$PLEXIL_HOME/compilers/plexilisp/plexil.el" "$1" --eval '(plexil)'
+EMACS="${EMACS-"$(command -v emacs)"}"
+if [ -z "$EMACS" ]
+then
+    echo 'Error: emacs not found. Cannot compile Plexilisp.' >&2
+    exit 1
+fi
+
+exec "$EMACS" --batch --no-site-file --load "$PLEXIL_HOME"/compilers/plexilisp/plexil.el "$1" --eval '(plexil)'
