Fixed quoting issues (namely, lack of them) in scripts/plexil-setup.sh and scripts/plexiltest
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@5346 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/plexiltest b/scripts/plexiltest
--- a/scripts/plexiltest
+++ b/scripts/plexiltest
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -25,32 +25,35 @@
 # TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# FIXME:
+#  - log_file appears to be unused
+
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo Error: Please set environment variable PLEXIL_HOME
-    echo to the full pathname of your 'plexil' or 'trunk' directory.
-    echo Exiting.
+    echo 'Error: Please set environment variable PLEXIL_HOME'
+    echo 'to the full pathname of your ''plexil'' directory.'
+    echo 'Exiting.'
     exit 1
 fi
 
-. $PLEXIL_HOME/scripts/plexil-setup.sh
+. "$PLEXIL_HOME/scripts/plexil-setup.sh"
 
 validate_file()
 {
-    if [ -z $1 ]
+    if [ -z "$1" ]
     then
         echo "Error: missing filename for $2 option"
         usage
         exit 2
-    elif [ ! -e $1 ]
+    elif [ ! -e "$1" ]
     then
         echo "Error: $1 does not exist"
         exit 1
-    elif [ -d $1 ]
+    elif [ -d "$1" ]
     then
         echo "Error: $1 is a directory"
         exit 1
-    elif [ ! -r $1 ]
+    elif [ ! -r "$1" ]
     then
         echo "Error: $1 cannot be read"
         exit 1
@@ -63,7 +66,7 @@ validNum()
     then
         echo "Error: Missing parameter for $2 option"
         exit 2
-    elif (( $1 <= 0 ))
+    elif [ "$1" -lt 0 ]
     then    	
   	    echo "Error: $1 is not a legal parameter for $2"
 	    exit 2
@@ -80,28 +83,27 @@ warn()
 
 checker()
 {
-    if [ ! -x $PLEXIL_HOME/scripts/checkPlexil ]
+    if [ ! -x "$PLEXIL_HOME/scripts/checkPlexil" ]
     then 
-	    echo Error: $PLEXIL_HOME/scripts/checkPlexil not found.	
+	    echo "Error: $PLEXIL_HOME/scripts/checkPlexil not found."
 	    exit 1
     fi
-    if [ ! -r $plan_nm ]
+    if [ ! -r "$plan_nm" ]
     then
-        echo Error: File $plan_nm does not exist, or is not readable.
+        echo "Error: File $plan_nm does not exist, or is not readable."
         exit 1
     fi
     echo "Checking plan..."
-    $PLEXIL_HOME/scripts/checkPlexil $plan_nm
-    if [ $? -gt 0 ]
+    if ! "$PLEXIL_HOME/scripts/checkPlexil" "$plan_nm"
     then
-	    echo Error: $plan_nm contains type errors. See the checker output for details.
+	    echo "Error: $plan_nm contains type errors. See the checker output for details."
         exit 1
 	fi
 }
 
 summarize()
 {
-    echo Running executive from $PLEXIL_HOME
+    echo "Running executive from $PLEXIL_HOME"
     echo "  Plan:           $plan_nm"
     if [ -n "$library_dirs" ]
     then
@@ -127,8 +129,8 @@ usage_text="Usage:\n\tplexiltest -p <plan> [-s <script file>] [-d <debug file>] 
 
 usage()
 {
-    echo -e $usage_text
-    echo -e "For more options enter 'plexiltest -help'"
+    printf "%s\n" "$usage_text"
+    echo "For more options enter 'plexiltest -help'"
 }
 
 help_text="Options:\n\
@@ -165,27 +167,26 @@ help_text="Options:\n\
 \t  Runs the exec with the supplied options, without checking them, and without starting the Viewer. \n\
 \t  Intended for use by the Plexil Viewer or other scripts."
 
-if [ $PLEXIL_EXECUTABLE ]
+if [ -n "$PLEXIL_EXECUTABLE" ]
 then
-    prog=$PLEXIL_EXECUTABLE
-elif [ -f $PLEXIL_HOME/bin/TestExec ] &&  [ -x $PLEXIL_HOME/bin/TestExec ]
+    prog="$PLEXIL_EXECUTABLE"
+elif [ -f "$PLEXIL_HOME/bin/TestExec" ] &&  [ -x "$PLEXIL_HOME/bin/TestExec" ]
 then
-    prog=$PLEXIL_HOME/bin/TestExec
-elif [ -f $PLEXIL_HOME/src/apps/TestExec/TestExec ] && [ -x $PLEXIL_HOME/src/apps/TestExec/TestExec ]
+    prog="$PLEXIL_HOME/bin/TestExec"
+elif [ -f "$PLEXIL_HOME/src/apps/TestExec/TestExec" ] && [ -x "$PLEXIL_HOME/src/apps/TestExec/TestExec" ]
 then
-    prog=$PLEXIL_HOME/src/apps/TestExec/TestExec
+    prog="$PLEXIL_HOME/src/apps/TestExec/TestExec"
 else
     echo "Error: Test Executive executable not found, aborting"
     exit 1
 fi
 
-$PLEXIL_HOME/scripts/plexil-check-prog $prog
+"$PLEXIL_HOME/scripts/plexil-check-prog" "$prog"
 
 quiet=""
 plan_nm="" 
 plan_cmd="" 
 script_name="" 
-guess_script=""
 script_cmd="" 
 libraries="" 
 library_dirs=""
@@ -193,7 +194,7 @@ debug_cmd=""
 check=""
 auto_run_cmd=""
 
-if [ ! $1 ]
+if [ ! "$1" ]
 then
   usage
   exit 1
@@ -201,32 +202,32 @@ fi
 
 while [ -n "$1" ] 
 do
-    save=$1
-    case $1 in
+    save="$1"
+    case "$1" in
 	    -a | -autorun )
-            auto_run_cmd=$1;;
+            auto_run_cmd="$1";;
 
 	    -b | -blocking )
-            block=$1;;	#enable viewer break point	
+            block="$1";;	#enable viewer break point	
 
 	    -ch | -check )
-            check=$1;;
+            check="$1";;
         
 	    -d | -debug )
             shift
-	        validate_file "$1" $save
+	        validate_file "$1" "$save"
             debug_cmd="-d $1";;
 
         --for-viewer)
-            automate=$1;;
+            automate="$1";;
 
 	    -h | -hostname )
             shift
 	        host_in="-h $1";;	#viewer host name
         
 	    -help )
-            echo -e $usage_text
-            echo -e $help_text
+            printf "%s\n" "$usage_text"
+            printf "%s\n" "$help_text"
 	        exit 0;;
 
 	    -L | -libraryPath )
@@ -247,7 +248,7 @@ do
         
 	    -l | -library )
             shift
-	        validate_file "$1" $save
+	        validate_file "$1" "$save"
 	        libraries="$libraries -l $1"
 	        lib_cmd="$lib_cmd-l $1 ";;
 
@@ -257,29 +258,29 @@ do
 
 	    -n | -port )
             shift
-	        validNum "$1" $save
+	        validNum "$1" "$save"
             port_in="$1"
 	        port_cmd="-n $1";;	#viewer port
         
 	    -p | -plan )
             shift
-            validate_file "$1" $save
-	        plan_nm=$1
+            validate_file "$1" "$save"
+	        plan_nm="$1"
 	        plan_cmd="-p $1";;
 
         -q | -quiet )
-            quiet=$1;;
+            quiet="$1";;
         
 	    -s | -script )
             shift
-            validate_file "$1" $save
-	        script_name=$1;;
+            validate_file "$1" "$save"
+	        script_name="$1";;
         
 	    -v | -viewer )
-            viewer=$1;;	#viewer listener enabled
+            viewer="$1";;	#viewer listener enabled
 
 	    -? )
-            echo 'Error: unrecognized option' $1
+            echo "Error: unrecognized option $1"
 	        usage
 	        exit 2;;
     esac
@@ -292,14 +293,14 @@ then
     # We do not expect a local Viewer to use the -h option.
     if [ -z "$plan_nm" ]
     then
-        echo Error: -p option is required.
+        echo 'Error: -p option is required.'
         usage
         exit 2
     fi
     
     if [ -z "$script_name" ]
     then
-        echo Error: -s option is required.
+        echo 'Error: -s option is required.'
         usage
         exit 2
     fi
@@ -318,7 +319,7 @@ then
     echo "RUN_TE_PID$$"
 
     #echo "$prog $plan_cmd $script_cmd $lib_cmd $lib_dirs_cmd $debug_cmd $viewer $port_cmd $block $quiet"
-    exec $prog $plan_cmd $script_cmd $lib_cmd $lib_dirs_cmd $debug_cmd $viewer $port_cmd $block $quiet
+    exec "$prog" "$plan_cmd" "$script_cmd" "$lib_cmd" "$lib_dirs_cmd" "$debug_cmd" "$viewer" "$port_cmd" "$block" "$quiet"
 fi
 
 # Check Viewer options
@@ -330,7 +331,7 @@ then
         # Check local port, if supplied
         if [ -n "$port_in" ]
         then
-            if ( echo `list_ports_in_use` | grep -q -v "\<${port_in}\>" )
+            if list_ports_in_use | grep -qv "\<${port_in}\>"
             then
                 echo "Error: No Viewer is listening on local port $port_in. Exiting."
                 exit 1
@@ -353,14 +354,14 @@ else
     if [ -z "$port_in" ]
     then
         # Find open local port
-        port_in=`find_open_port`
+        port_in="$(find_open_port)"
         if [ -z "$port_in" ]
         then
             echo "Unable to find an open local port for Viewer communications. Exiting."
             exit 1
         fi
         port_cmd="-n $port_in"
-    elif ( echo `list_ports_in_use` | grep -q "\<${port_in}\>" )
+    elif list_ports_in_use | grep -q "\<${port_in}\>"
     then
         echo "Error: Port $port_in is in use. Exiting."
         exit 1
@@ -385,7 +386,7 @@ then
 fi
 
 # The plan file's extension, used to compute guessed script name.
-ext=".`echo $plan_nm | awk -F. '{print $2}'`"
+ext=".$(echo "$plan_nm" | awk -F. '{print $2}')"
 
 # If no more arguments, or next argument -l, check for candidate scripts.
 # Otherwise, next argument must be script.
@@ -394,32 +395,32 @@ if [ -n "$script_name" ]
 then
     if [ ! -f "$script_name" ]
     then
-        echo Error: Script $script_name does not exist.
+        echo "Error: Script $script_name does not exist."
         exit 1
     elif [ ! -r "$script_name" ]
     then
-        echo Error: Script file $script_name is not readable.
+        echo "Error: Script file $script_name is not readable."
         exit 1
     fi
 else
     # Attempt to guess based on plan name
-    script_candidate=`basename $plan_nm $ext`.psx
-    if [ -e $script_candidate ]
+    script_candidate="$(basename "$plan_nm" "$ext")".psx
+    if [ -e "$script_candidate" ]
     then
-        script_name=$script_candidate
-    elif [ -e scripts/$script_candidate ]
+        script_name="$script_candidate"
+    elif [ -e "scripts/$script_candidate" ]
     then
-        script_name=scripts/$script_candidate
-    elif [ -e ../scripts/$script_candidate ]        
+        script_name="scripts/$script_candidate"
+    elif [ -e "../scripts/$script_candidate" ]        
     then
-        script_name=../scripts/$script_candidate
+        script_name="../scripts/$script_candidate"
     fi
 fi
 
 if [ -z "$script_name" ]
 then
-    warn "No simulation script specified; using empty script."
-    script_name=$PLEXIL_HOME/examples/empty.psx
+    warn 'No simulation script specified; using empty script.'
+    script_name="$PLEXIL_HOME/examples/empty.psx"
 fi
 
 script_cmd="-s $script_name"
@@ -437,9 +438,9 @@ if [ -n "$viewer" ]
 then
     # Launch the viewer, which will in turn invoke this script again with the automate flag
     #echo "plexil -plexiltest $plan_cmd $script_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $host_cmd $port_cmd $check $block $auto_run_cmd"
-    exec plexil -plexiltest $plan_cmd $script_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $host_cmd $port_cmd $check $block $auto_run_cmd
+    exec plexil -plexiltest "$plan_cmd" "$script_cmd" "$lib_dirs_cmd" "$lib_cmd" "$debug_cmd" "$host_cmd" "$port_cmd" "$check" "$block" "$auto_run_cmd"
 else
     # User doesn't want viewer
     #echo "$prog $plan_cmd $script_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $block"
-    exec $prog $plan_cmd $script_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $block
+    exec "$prog" "$plan_cmd" "$script_cmd" "$lib_dirs_cmd" "$lib_cmd" "$debug_cmd" "$block"
 fi
