Heavily revised, work in progress
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@4274 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/plexilexec b/scripts/plexilexec
--- a/scripts/plexilexec
+++ b/scripts/plexilexec
@@ -1,6 +1,6 @@
-#! /bin/bash
+#! /usr/bin/env bash
 
-# Copyright (c) 2006-2014, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2015, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -25,75 +25,20 @@
 # TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-#Validate file
-valid()
-{
-  if [ ! -e $1 ] && [ $quiet = 1 ]
-    then
-      echo "WARNING: $1 does not exist"
-  fi
-  return
-}
-
-warn()
-{
-   if [ $quiet = 1 ]
-     then
-       echo "$1"
-   fi
-}
-
-#There are ranges below 22000 which netstat does not detect
-portscan()
-{
-for((j=65400;j<=65420;++j))
-do
-if [ "$platform" = "Darwin" ]
-  then
-    tport=`netstat -a | grep $j`
-  else
-    tport=`netstat -l | grep $j`
-fi    
-    if [ "${tport:-FALSE}" = FALSE ] && [ ! -f /tmp/.Luv_$j ] ; then
-    	echo "-n $j"
-	return
-    fi    
-done
-return
-}
-usage="Usage: plexilexec [-p <plan>] [-s] [-v [-h <hostname>] [-n <portnumber>] [-b]] [-d <debug file>] \
-[-ch] [-c <interface config>] [-l <library>]* \n\n\
-For more options enter 'plexilexec -help'"
+#
+# There are 3 primary use cases for this script:
+# 1. User wants to run the Universal Exec from a local Viewer.
+# 2. User wants to run the UE, without a local Viewer
+#    (but possibly with a remote one).
+# 3. Viewer is running the UE on behalf of a user.
+#
+# Case 1 does error checking on the supplied arguments and passes them off
+# to the Viewer.
+# Case 2 does error checking on the arguments and runs the UE directly.
+# Case 3 presumes the arguments are correct and runs the UE directly.
+#
 
 # An optional environment variable PLEXIL_EXECUTABLE names an alternate executable.
-
-help=" Other options:\n\
-\n\
- -p | -plan <plan> \n\
-\t	specify PLEXIL plan (required) \n\
- -c | -config <config> \n\
-\t 	specifies an interface configuration file (defaulting to interface-config.xml)\n\
- -q | -quiet \n\
-\t 	suppresses a leading printed summary and default debug messages.\n\
- -v | -viewer \n\
-\t 	requests that plan state be transmitted to the Plexil viewer.\n\
- -h | -hostname <name> \n\
-\t 	hostname of viewer\n\
- -n | -port <number> \n\
-\t 	portnumber of viewer\n\
- -b | -blocking \n\
-\t 	enables breakpoints in viewer (recommended)\n\
- -d | -debug <file name> \n\
-\t 	debug file (default is Debug.cfg)\n\
- -ch | -check \n\
-\t 	runs the PLEXIL static checker prior to executing plan\n\
- -l | -library <file name>\n\
-\t 	specifies a plan library (.plx file)\n\
- -L | -libraryPath <directory name>\n\
-\t 	specifies a directory for finding plan library files\n\
--? | -help \n\
-\t	shows this message of options"
-# -a used only for viewer acquire PID
 
 if [ -z "$PLEXIL_HOME" ]
 then
@@ -105,8 +50,126 @@ fi
 
 . $PLEXIL_HOME/scripts/plexil-setup.sh
 
-#separate command-line from plexexec output
-echo
+#Validate file
+validate_file()
+{
+    if [ -z $1 ]
+    then
+        echo "Internal error: missing filename in call to valid()"
+        exit 3
+    fi
+    if [ -n "$quiet" ]
+    then
+        return
+    fi
+    if [ ! -e $1 ]
+    then
+        echo "Warning: $1 does not exist"
+    elif [ -d $1 ]
+    then
+        echo "Warning: $1 is a directory"
+    elif [ ! -r $1 ]
+    then
+        echo "Warning: $1 cannot be read"
+    fi
+}
+
+warn()
+{
+   if [ -z "$quiet" ]
+   then
+       echo "$1"
+   fi
+}
+
+checker()
+{
+    if [ ! -x $PLEXIL_HOME/scripts/checkPlexil ]
+    then 
+	    echo Error: $PLEXIL_HOME/scripts/checkPlexil not found.	
+	    exit 1
+    fi
+    if [ ! -r $plan_nm ]
+    then
+        echo Error: File $plan_nm does not exist, or is not readable.
+        exit 1
+    fi
+    echo "Checking plan..."
+    $PLEXIL_HOME/scripts/checkPlexil $plan_nm
+    if [ $? -gt 0 ]
+    then
+	    echo Error: $plan_nm contains type errors. See the checker output for details.
+        exit 1
+	fi
+}
+
+summarize()
+{
+    echo Running executive from $PLEXIL_HOME
+    if [ -n "$plan_nm" ]
+    then
+        echo "  Plan:           $plan_nm"
+    else
+        echo "  No plan"
+    fi
+    echo "  Configuration:  $config_nm"
+    if [ -n "$library_dirs" ]
+    then
+        echo "  Library path:   $library_dirs"
+    fi
+    if [ -n "$libraries" ]
+    then
+        echo "  Libraries:      $libraries"
+    fi
+    if [ -n "$host_in" ]
+    then
+        echo "  Viewer host:    $host_in"
+    fi
+    if [ -n "$port_in" ]
+    then
+        echo "  Viewer port:    $port_in"
+    fi
+    echo
+}
+
+usage_text="Usage:\n\tplexilexec [-p <plan>] [-c <interface config>] [-d <debug file>] [-L <library dir>]* [-l <library>]*\
+ [-v [-h <hostname>] [-n <portnumber>] [-b]] [-ch] [-q] \n"
+
+usage()
+{
+    echo -e $usage_text
+    echo -e "For more options enter 'plexilexec -help'"
+}
+
+help_text=" Options:\n\
+\n\
+ -help \n\
+\t	displays this message\n\
+ -p | -plan <plan> \n\
+\t	The plan to run \n\
+ -c | -config <config> \n\
+\t 	Interface configuration file (default interface-config.xml) \n\
+ -d | -debug <file name> \n\
+\t 	Debug configuration file (default is Debug.cfg) \n\
+ -L | -libraryPath <directory name> \n\
+\t 	A directory to search for plan library files (option may be repeated) \n\
+ -l | -library <file name> \n\
+\t 	A plan library to load; may be node name or filename (option may be repeated) \n\
+ -q | -quiet \n\
+\t 	Minimize output \n\
+ -v | -viewer \n\
+\t 	Starts the Plexil Viewer \n\
+ -h | -hostname <name> \n\
+\t 	Port number to use for Viewer \n\
+ -b | -blocking \n\
+\t 	Name of remote host where Viewer is running \n\
+ -n | -port <number> \n\
+\t 	Enables breakpoints in Viewer \n\
+ -ch | -check \n\
+\t 	Runs the PLEXIL static checker prior to executing plan \n\
+ -a | -nochecks \n\
+\t  Runs the exec with the supplied options, without checking them, and without the Viewer. \n\
+\t  Intended for use by the Plexil Viewer or other scripts."
 
 if [ $PLEXIL_EXECUTABLE ]
 then
@@ -128,7 +191,7 @@ default_config="${default_config_path}/${default_config_name}"
 
 platform=`uname`
 no_plan=0 #assume plan required
-quiet=1 #quiet default
+quiet="" #quiet default
 plan_nm="" #plan name
 plan_cmd="" #plan command
 config_nm="" #interface config name
@@ -136,205 +199,234 @@ config_cmd="" #interface config command
 libraries="" #library files
 library_dirs="" #library files
 debug_file="" #debug file
-check="false" #run static checker
-DEFAULT_PORT=9787
-DEFAULT_HOST=127.0.0.1
+check="" #run static checker
 
 if [ ! $1 ]
-  then
-  echo -e $usage
+then
+  usage
   exit 1
 fi
 
-if [ $# = 1 ] && [ $* = "-v" ] ; then
-  plexil
-  exit 1
-fi
-
-for i in $*
+while [ -n "$1" ]
 do
     case $1 in
-        -quiet | -q ) quiet=0;;	
-	-p | -plan )
-	shift
-	plan_nm=$1	
-	plan_cmd="-p $plan_nm";;
-	-c | -config )
-	shift
-	config_nm=$1	
-	config_cmd="-c $config_nm";;
-	-l | -library ) shift
-	valid $1	
-	libraries="$libraries -l $1";;
-	-L | -libraryPath ) shift
-	valid $1	
-	library_dirs="$library_dirs -L $1";;
-	-d | -debug ) shift
-	valid $1
-	debug_file="-d $1";;
-	-v | -viewer ) viewer="-v";;	#viewer listener enabled	
-	-h | -hostname ) shift
-	host_in="-h $1";;	#viewer host name
-	-n | -port ) shift
-	port_in="-n $1"
-	    skip=1;;	#viewer port
-	-b | -blocking ) block="-b";;	#enable viewer break point	
-	-ch | -check ) check="true";;	
-	-a ) automate="true";;
-	-help ) echo -e $help
-	  exit 2;;
-	-? ) echo 'Error: missing argument for option' $1
-	  echo -e $usage
-	  exit 2;;  
+        
+	    -a | -nochecks )
+            automate=$1;;
+
+	    -b | -blocking )
+            block=$1;;
+
+	    -c | -config )
+	        shift
+	        config_nm=$1;;
+
+	    -ch | -check )
+            check=$1;;
+
+	    -d | -debug )
+            shift
+	        validate_file $1
+	        debug_file="-d $1";;
+
+	    -h | -hostname )
+            shift
+	        host_in="$1";;
+
+	    -help )
+            echo -e $usage_text
+            echo -e $help_text
+	        exit 0;;
+
+	    -L | -libraryPath )
+            shift
+            if [ ! -r "$1" ] || [ ! -d "$1" ]
+            then
+                echo "Warning: $1 is not a readable directory. Ignoring."
+            else
+                library_dirs="$library_dirs$1 "
+	            lib_dirs_cmd="$lib_dirs_cmd-L $1 "
+            fi;;
+
+	    -l | -library )
+            shift
+	        validate_file $1	
+            libraries="$libraries$1 "
+	        lib_cmd="$lib_cmd-l $1 ";;
+
+	    -n | -port )
+            shift
+	        port_in=$1;;	#viewer port
+
+	    -p | -plan )
+	        shift
+	        plan_nm=$1	
+	        plan_cmd="-p $plan_nm";;
+
+        -q | -quiet )
+            quiet=$1;;
+
+	    -v | -viewer )
+            viewer=$1;;	#viewer listener enabled	
+
+	    * )
+            echo 'Error: unrecognized option' "'$1'"
+	        usage
+	        exit 2;;  
     esac
     shift
 done
 
-# Check the plan's existence
-if [ -z "$plan_nm" ] 
-  then
-    no_plan=1
-fi    
-
-# Check if user typed invalid plan
-if [ ! -e "$plan_nm" ] && [ "$no_plan" = 0 ]
-  then
-        echo Error: Plan $plan_nm, does not exist.
-        exit 1    
+if [ -n "$automate" ]
+then
+    # Just Do It - presume the Viewer knows what it's doing.
+    # We do not expect a local Viewer to use the -h option.
+    if [ -n "$plan_nm" ] && [ -n "$check" ]
+    then
+        checker
+    fi
+	config_cmd="-c $config_nm"
+    if [ -z "$quiet" ]
+    then
+        summarize
+    fi
+    if [ -n "$port_in" ]
+    then
+        port_cmd="-p $port_in"
+    fi
+    echo "RUN_UE_PID$$"
+    exec $prog $plan_cmd $config_cmd $lib_cmd $lib_dirs_cmd $debug_cmd $viewer $port_cmd $block $quiet
+    # *** debug use only ***
+    #echo $prog $plan_cmd $config_cmd $lib_cmd $lib_dirs_cmd $debug_cmd $viewer $port_cmd $block $quiet
+    #exit 0
 fi
 
-# Redefine current path config to look for dummy config on current path
-if [ -z "$config_nm" ] || [ ! -e "$config_nm" ]
-   then
-        if [ ! -e "$current_config" ] ; then
-	  current_config=$default_config_name
-	fi
+if [ -n "$block" ]
+then
+    if [ -z "$viewer" ] && [ -z "$host_in" ] && [ -z "$port_in" ]
+    then
+        warn "Warning: $block specified but Viewer not in use. Ignoring."
+        block=""
+    fi
 fi
 
-# Check the config's existence
-if [ -z "$config_nm" ] || [ ! -e "$config_nm" ]
-  then  
-  if [ -e "$current_config" ]
+# Check if plan name valid
+if [ -n "$plan_nm" ] && [ ! -f "$plan_nm" ]
+then
+    echo Error: Plan file $plan_nm does not exist.
+    exit 1
+elif [ ! -r "$plan_nm" ]
+then
+    echo Error: Plan file $plan_nm is not readable.
+    exit 1
+fi
+
+# Check the supplied config
+if [ -z "$config_nm" ]
+then
+    warn "Warning: no configuration file specified."
+elif [ ! -r $config_nm ]
+then
+    warn "Warning: configuration file $config_nm not found"
+    config_nm=""
+fi
+
+# Use default config if needed
+if [ -z "$config_nm" ]
+then  
+    if [ -r "$current_config" ]
     then   
-    warn "Warning: using local config: $current_config"
-    config_nm=$current_config
-    #use default blank config if plan is loaded
-    elif [ -e "$default_config" ] && [ -e "$plan_nm" ]
-      then      
-        default_msg=": $config_nm,"
-        warn "Error: No config defined or Config${config_nm:+$default_msg} does not exist."
-        warn "Warning: using default config: $default_config"
-        config_nm=$default_config
-	#prevent idle exec from default blank config call
-    elif [ $no_plan = 1 ]
-      then
-          echo Error: No config defined or on current path and no plan.
-          exit 1
-    else 
-      echo Error: Default config $default_config does not exist.
-      exit 1
-  fi  
-  config_cmd="-c $config_nm"
-fi
-
-#host workaround to skip pass thru check
-if [ -n "$host_in" ]
-  then
-  skip=""
-fi
-
-# Check pass thru port into viewer
-if [ "$viewer" = "-v" ] && [ "$skip" = "1" ]
-  then
-  temphelper=$port_in  
-  if [ "${port_in//[^0-9]/}" -lt 1024 ] && [ $quiet = 1 ] ; then
-    echo "Warning: ${port_in//[^0-9]/} is within frequently used port range, usage of this port is not recommended"
-  fi
-  if [ "$platform" = "Darwin" ]
-  then
-    testOpen=`netstat -a | grep ${temphelper//[^0-9]}`
-  else
-    testOpen=`netstat -l | grep ${temphelper//[^0-9]}`
-  fi
-  if [ -z "$testOpen" ] ; then
-      warn "Warning: script may not detect ports listening < 22000"      
-    if [ ${temphelper//[^0-9]} -gt 22000 ] ; then
-      echo "local Viewer is not listening on ${temphelper//[^0-9]}, exiting"
-      exit 1
+        config_nm=$current_config
+    elif [ ! -r "$default_config" ]
+    then
+         echo Error: No configuration file specified and defaults cannot be found.
+         exit 1
+    else
+	    config_nm=$default_config
     fi
-  fi
+    warn "Using default configuration file $current_config"
 fi
+config_cmd="-c $config_nm"
 
-#host re-enable to pass check
-if [ -n "$host_in" ]
-  then
-  skip=1
-fi
-  
-# Check for port number
-if [ "$viewer" = "-v" ] ; then
-  host=${host_in:="-h $DEFAULT_HOST"}
-  port=${port_in:=`portscan`}
-    if [ -z "$port" ] ; then
-      echo "Exceeds Maximum number of allowable viewer instances.  Please close
-      an instance prior to execution"
-      exit 1
-  fi
-  if [ -z "$skip" ] ; then
-    plexil ${port//[^0-9]/}
-    until [ -f /tmp/.Luv_${port//[^0-9]/} ]
-      do
-	:
-    done    
-    sleep 1
-  elif [ -z "$automate" ] ; then
-    if [ ! -f /tmp/.Luv_${port//[^0-9]/} ] && [ $quiet = 1 ] ; then
-      echo "Warning: Viewer is not listening on port ${port//[^0-9]/}"
+# Check Viewer options
+if [ -z "$viewer" ]
+then
+    # No local Viewer
+    if [ -z "$host_in" ]
+    then
+        # Check local port, if supplied
+        if [ -n "$port_in" ]
+        then
+            if ( echo `list_ports_in_use` | grep -q -v "\<${port_in}\>" )
+            then
+                echo "Error: No Viewer is listening on local port $port_in. Exiting."
+                exit 1
+            fi
+        fi
+    elif [ -z "$port_in" ]
+    then
+        echo "Error: Viewer host $host_in specified, but no port was supplied. Exiting."
+        exit 1
     fi
-  fi      
+    # TODO: Bounds check port number
+elif [ -n "$host_in" ]
+then
+    echo "Error: -h (remove Viewer host) and -v (local Viewer) may not be combined. Exiting."
+    exit 1
+else
+    # Local Viewer requested
+    if [ -z "$port_in" ]
+    then
+        # Find open local port
+        port_in=`find_open_port`
+        if [ -z "$port_in" ]
+        then
+            echo "Unable to find an open local port for Viewer communications."
+            exit 1
+        fi
+    elif ( echo `list_ports_in_use` | grep -q "\<${port_in}\>" )
+    then
+        echo "Error: Port $port_in is in use. Exiting."
+        exit 1
+    fi
 fi
 
-if [ ! "$viewer" = "-v" ] && [ "$port_in" ] ; then
-  echo "Error: -n option requires Viewer, please add -v option"
-  exit 1
+if [ -n "$host_in" ]
+then
+    host_cmd="-hostname $host_in"
 fi
 
+if [ -n "$port_in" ]
+then
+    port_cmd="-p $port_in"
+fi
+     
 # Run default debug
-if [ -z "$debug_file" ] && [ $quiet = 1 ]
-  then
+if [ -z "$debug_file" ] && [ -z "$quiet" ]
+then
     debug_file="-d Debug.cfg"
 fi
 
 # Check plan for errors
-if [ "$check" = "true" ] && [ -f $PLEXIL_HOME/scripts/checkPlexil ]
-  then 
-       echo "Checking Plan..."
-       $PLEXIL_HOME/scripts/checkPlexil $plan_nm
-       if [ ! -e "$plan_nm" ] && [ $? -gt 0 ]
-         then
-	   echo Error: $plan_nm, contains runtime error
-           exit 1
-	fi
-    elif [ ! -f $PLEXIL_HOME/scripts/checkPlexil ]
-      then
-	echo Error: $PLEXIL_HOME/scripts/checkPlexil not found.	
-	exit 1
-fi  
+if [ -n "$check" ]
+then
+    checker
+fi
+
+#separate command-line from plexexec output
+echo
 
 # Print summary if desired
-if [ $quiet -eq 1 ] 
-  then
-    echo Running executive from $PLEXIL_HOME
-    echo "  Plan:      $plan_nm"
-    echo "  Configuration:    $config_nm"
-    echo "  Libraries: $libraries"
-    echo "  Library directories: $library_dirs"
-    echo "  PORT:      ${port//[^0-9]/}"    
-    echo
+if [ -z "$quiet" ] 
+then
+    summarize
 fi
 
-if [ "$automate" = "true" ]
+if [ -n "$viewer" ]
 then
-    echo "RUN_UE_PID$$"
+    #echo "plexil $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_file $viewer $host_cmd $port_cmd $block"
+    exec plexil $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_file $viewer $host_cmd $port_cmd $block
+else
+    #echo "$prog $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_file $viewer $host_cmd $port_cmd $block"
+    exec $prog $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_file $viewer $host_cmd $port_cmd $block
 fi
-exec $prog $plan_cmd $config_cmd $debug_file $viewer $host $port $block $library_dirs $libraries
