scripts/plexil: If PLEXIL_HOME not set, make an educated guess as to its value

diff --git a/scripts/plexil b/scripts/plexil
--- a/scripts/plexil
+++ b/scripts/plexil
@@ -1,6 +1,6 @@
-#! /bin/sh
+#! /bin/sh -e
 
-# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2021, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -26,13 +26,29 @@
 # USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 # Check environment variables and UE executable
+guess_plexil_home()
+{
+    # This script file is expected to be in $PLEXIL_HOME/script
+    local THIS_DIR="$( cd "$(dirname "$(command -v "$0")")" && pwd -P )"
+    cd "$THIS_DIR/.." && pwd -P
+}
+
 if [ -z "$PLEXIL_HOME" ]
-  then
-    echo Error: Please set environment variable PLEXIL_HOME
-    echo to the full pathname of your root 'plexil' directory.
+then
+    PLEXIL_HOME="$(guess_plexil_home)"
+    export PLEXIL_HOME
+    echo "Defaulting PLEXIL_HOME to $PLEXIL_HOME"
+fi
+
+if [ ! -r "$PLEXIL_HOME/scripts/plexil-setup.sh" ]
+then
+    echo 'Error: Environment variable PLEXIL_HOME is set incorrectly.' >&2
+    echo 'Please set it to the full pathname of the PLEXIL source directory.' >&2
     exit 1
 fi
 
+export PLEXIL_HOME
+# shellcheck source=./plexil-setup.sh
 . "$PLEXIL_HOME"/scripts/plexil-setup.sh
 
 prog="$PLEXIL_HOME"/viewers/pv/luv.jar
