checkWarn -> echo
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-3@3170 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/plexiltest b/scripts/plexiltest
--- a/scripts/plexiltest
+++ b/scripts/plexiltest
@@ -128,7 +128,8 @@ elif [ -f $PLEXIL_HOME/src/apps/TestExec/TestExec ]
 then
     prog=$PLEXIL_HOME/src/apps/TestExec/TestExec
 else
-    checkWarn "Test Executive executable not found, aborting"
+    echo "Test Executive executable not found, aborting"
+    exit 1
 fi
 
 $PLEXIL_HOME/scripts/plexil-check-prog $prog
