plexilexec, plexiltest: Use utility functions in script-utils.sh; if PLEXIL_HOME not set, make an educated guess about its value

diff --git a/scripts/plexilexec b/scripts/plexilexec
--- a/scripts/plexilexec
+++ b/scripts/plexilexec
@@ -1,6 +1,6 @@
-#! /bin/sh
+#! /bin/sh -e
 
-# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2021, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -40,75 +40,83 @@
 
 # An optional environment variable PLEXIL_EXECUTABLE names an alternate executable.
 
+guess_plexil_home()
+{
+    # This script file is expected to be in $PLEXIL_HOME/script
+    cd "$(dirname "$(dirname "$(command -v "$0")")")" && pwd -P
+}
+
 if [ -z "$PLEXIL_HOME" ]
 then
-    echo 'Error: Please set environment variable PLEXIL_HOME'
-    echo "to the full pathname of your 'plexil' or 'trunk' directory."
-    echo 'Exiting.'
+    PLEXIL_HOME="$(guess_plexil_home)"
+    export PLEXIL_HOME
+    echo "Defaulting PLEXIL_HOME to $PLEXIL_HOME"
+fi
+
+if [ ! -r "$PLEXIL_HOME/scripts/plexil-setup.sh" ]
+then
+    echo "$(basename "$0"): Environment variable PLEXIL_HOME is set incorrectly." >&2
+    echo 'Please set it to the full pathname of the PLEXIL source directory' >&2
     exit 1
 fi
 
+export PLEXIL_HOME
+# shellcheck source=./plexil-setup.sh
 . "$PLEXIL_HOME"/scripts/plexil-setup.sh
 
-plexil_check_prog()
+usage()
 {
-    if [ ! -e "$1" ]
-    then
-        echo "Error: $1 does not exist."
-        echo 'You probably need to build it.'
-        exit 1
-    fi
+    cat <<EOF
+Usage:
+    plexilexec [-p <plan>] [-c <interface config>] [-d <debug file>] [-L <library dir>]* [-l <library>]* [-v [-h <hostname>] [-n <portnumber>] [-b]] [-a] [-ch] [-q]
+
+For more options enter '$(basename "$0") -help'
+
+EOF
 }
 
-validate_file()
+help()
 {
-    if [ -z "$1" ]
-    then
-        echo "Error: missing filename for $2 option"
-        usage
-        exit 2
-    elif [ ! -e "$1" ]
-    then
-        echo "Error: $1 does not exist"
-        exit 1
-    elif [ -d "$1" ]
-    then
-        echo "Error: $1 is a directory"
-        exit 1
-    elif [ ! -r "$1" ]
-    then
-        echo "Error: $1 cannot be read"
-        exit 1
-    fi
+    cat <<EOF
+Usage:
+    plexilexec [-p <plan>] [-c <interface config>] [-d <debug file>] [-L <library dir>]* [-l <library>]* [-v [-h <hostname>] [-n <portnumber>] [-b]] [-a] [-ch] [-q]
+
+ Options:
+ -help 
+    displays this message
+ -p | -plan <plan>
+    The plan to run
+ -c | -config <config> 
+    Interface configuration file (default interface-config.xml) 
+ -d | -debug <file name> 
+    Debug configuration file (default is Debug.cfg) 
+ -L | -libraryPath <directory name> 
+    A directory to search for plan library files (option may be repeated) 
+ -l | -library <file name> 
+    A plan library to load; may be node name or filename (option may be repeated) 
+ -q | -quiet 
+    Minimize output 
+ -v | -viewer 
+    Starts the Plexil Viewer 
+ -b | -blocking 
+    Enables breakpoints in Viewer 
+ -h | -hostname <name> 
+    Name of remote host where Viewer is running
+ -n | -port <number> 
+    Port number to use for Viewer 
+ -ch | -check 
+    Runs the PLEXIL static checker prior to executing plan 
+ -a | -autorun 
+    Runs the specified plan immediately at Viewer startup 
+ --for-viewer 
+    Runs the exec with the supplied options, without checking them, and without starting the Viewer. 
+    Intended for use by the Plexil Viewer or other scripts.
+EOF
 }
 
-warn()
-{
-   if [ -z "$quiet" ]
-   then
-       echo "$1"
-   fi
-}
-
-checker()
-{
-    if [ ! -x "$PLEXIL_HOME"/scripts/checkPlexil ]
-    then 
-	    echo "Error: $PLEXIL_HOME/scripts/checkPlexil not found."
-	    exit 1
-    fi
-    if [ ! -r "$plan_nm" ]
-    then
-        echo "Error: File $plan_nm does not exist, or is not readable."
-        exit 1
-    fi
-    echo "Checking plan..."
-    if ! "$PLEXIL_HOME"/scripts/checkPlexil "$plan_nm"
-    then
-	echo Error: $plan_nm contains type errors. See the checker output for details.
-        exit 1
-    fi
-}
+# Source command parsing helper functions
+# shellcheck source=./script-utils.sh
+. "$PLEXIL_HOME"/scripts/script-utils.sh
 
 summarize()
 {
@@ -139,47 +147,6 @@ summarize()
     echo
 }
 
-usage_text="Usage:
-	plexilexec [-p <plan>] [-c <interface config>] [-d <debug file>] [-L <library dir>]* [-l <library>]* [-v [-h <hostname>] [-n <portnumber>] [-b]] [-a] [-ch] [-q]
-"
-
-usage()
-{
-    printf "%s\n" "$usage_text"
-    echo "For more options enter 'plexilexec -help'"
-}
-
-help_text=" Options:
- -help 
-	displays this message
- -p | -plan <plan>
-	The plan to run
- -c | -config <config> 
-	Interface configuration file (default interface-config.xml) 
- -d | -debug <file name> 
-	Debug configuration file (default is Debug.cfg) 
- -L | -libraryPath <directory name> 
-	A directory to search for plan library files (option may be repeated) 
- -l | -library <file name> 
-	A plan library to load; may be node name or filename (option may be repeated) 
- -q | -quiet 
-	Minimize output 
- -v | -viewer 
-	Starts the Plexil Viewer 
- -b | -blocking 
-	Enables breakpoints in Viewer 
- -h | -hostname <name> 
-	Name of remote host where Viewer is running
- -n | -port <number> 
-	Port number to use for Viewer 
- -ch | -check 
-	Runs the PLEXIL static checker prior to executing plan 
- -a | -autorun 
-	Runs the specified plan immediately at Viewer startup 
- --for-viewer 
-	Runs the exec with the supplied options, without checking them, and without starting the Viewer. 
-	Intended for use by the Plexil Viewer or other scripts."
-
 if [ -n "$PLEXIL_EXECUTABLE" ] && [ -x "$PLEXIL_EXECUTABLE" ]
 then
     prog="$PLEXIL_EXECUTABLE"
@@ -190,7 +157,7 @@ elif [ -x "$PLEXIL_HOME"/bin/universalExec/universalExec ]
 then
     prog="$PLEXIL_HOME"/bin/universalExec/universalExec
 else
-    echo 'Error: Plexil executable not found, aborting' >&2
+    echo "$(basename "$0"): Plexil executable not found, aborting" >&2
     exit 1
 fi
 
@@ -214,94 +181,108 @@ auto_run_cmd='' # Viewer autorun option
 
 if [ -z "$1" ]
 then
-  usage
-  exit 1
+    usage
+    exit 1
 fi
 
 while [ -n "$1" ]
 do
-    save="$1"
     case "$1" in
         
-	-a | -autorun )
+        -a | -autorun )
             auto_run_cmd="$1";;
 
-	-b | -blocking )
+        -b | -blocking )
             block="$1";;
 
-	-c | -config )
-	    shift
-	    config_nm="$1";;
+        -c | -config )
+            shift
+            config_nm="$1";;
 
-	-ch | -check )
+        -ch | -check )
             check="$1";;
 
-	-d | -debug )
+        -d | -debug )
+            validate_file "$1" "$2"
+            debug_cmd="-d $2"
             shift
-	    validate_file "$1" "$save"
-            debug_cmd="-d $1";;
+            ;;
 
         --for-viewer )
-	    automate="$1";;
+            automate="$1";;
 
-	-h | -hostname )
-	    if [ -n "$2" ]
-	    then
-		shift
-		host_in="$1"
-	    else
-		printf "%s\n" "$usage_text"
-		printf "%s\n" "$help_text"
-		exit 0
-	    fi;;
 
-	-help | --help )
-	    printf "%s\n" "$usage_text"
-	    printf "%s\n" "$help_text"
-	    exit 0;;
-
-	-L | -libraryPath )
-            shift
-            if [ -z "$1" ]
+        -h )
+            # Is it a help request or a host name?
+            if [ -z "$2" ]
             then
-                echo "Error: missing directory name for $save option"
+                # Help request
+                help
+                exit 0
+            fi
+            validate_host "$1" "$2"
+            host_in="-h $2"       #viewer host name
+            shift
+            ;;
+        
+        -hostname )
+            validate_host "$1" "$2"
+            host_in="-h $2"       #viewer host name
+            shift
+            ;;
+
+        -help | --help )
+            help
+            exit 0
+            ;;
+
+        -L | -libraryPath )
+            if [ -z "$2" ]
+            then
+                echo "$(basename "$0"): missing directory name for $1 option" >&2
                 usage
                 exit 2
-            elif [ ! -r "$1" ] || [ ! -d "$1" ]
+            elif [ ! -r "$2" ] || [ ! -d "$2" ]
             then
-                echo "Error: $1 is not a readable directory."
+                echo "$(basename "$0"): $1 is not a readable directory." >&2
                 exit 1
             else
-                library_dirs="$library_dirs$1 "
-	        lib_dirs_cmd="$lib_dirs_cmd-L $1 "
-            fi;;
-
-	-l | -library )
+                library_dirs="$library_dirs$2 "
+                lib_dirs_cmd="$lib_dirs_cmd-L $2 "
+            fi
             shift
-	    validate_file "$1" "$save"
-            libraries="$libraries$1 "
-	    lib_cmd="$lib_cmd-l $1 ";;
+            ;;
 
-	-n | -port )
+        -l | -library )
+            validate_file "$1" "$2"
+            libraries="$libraries$2 "
+            lib_cmd="$lib_cmd-l $2 "
             shift
-	    port_in="$1";;	#viewer port
+            ;;
 
-	-p | -plan )
-	    shift
-            validate_file "$1" "$save"
-	    plan_nm="$1"	
-	    plan_cmd="-p $plan_nm";;
+        -n | -port )
+            validate_port "$1" "$2"
+            port_in="$2"    #viewer port
+            shift
+            ;;
+
+        -p | -plan )
+            validate_file "$1" "$2"
+            plan_nm="$2"
+            plan_cmd="-p $2"
+            shift
+            ;;
 
         -q | -quiet )
             quiet="$1";;
 
-	-v | -viewer )
-            viewer="$1";;	#viewer listener enabled	
+        -v | -viewer )
+            viewer="$1";;   #viewer listener enabled    
 
-	* )
-            echo 'Error: unrecognized option' "'$1'"
-	    usage
-	    exit 2;;  
+        * )
+            echo "$(basename "$0"): unrecognized option \"$1\"" >&2
+            usage
+            exit 2;;  
     esac
     shift
 done
@@ -325,7 +306,8 @@ then
     fi
     echo "RUN_UE_PID$$"
 
-    #echo $prog $plan_cmd $config_cmd $lib_cmd $lib_dirs_cmd $debug_cmd $viewer $port_cmd $block $quiet
+    # The unquoted expansions are deliberate
+    # shellcheck disable=SC2086
     exec "$prog" $plan_cmd $config_cmd $lib_cmd $lib_dirs_cmd $debug_cmd $viewer $port_cmd $block $quiet
 fi
 
@@ -356,10 +338,10 @@ then
         config_nm="$current_config"
     elif [ ! -r "$default_config" ]
     then
-         echo Error: No configuration file specified and defaults cannot be found.
-         exit 1
+        echo "$(basename "$0"): No configuration file specified and defaults cannot be found." >&2
+        exit 1
     else
-	config_nm="$default_config"
+        config_nm="$default_config"
     fi
     warn "Using default configuration file $config_nm"
 fi
@@ -376,19 +358,19 @@ then
         then
             if list_ports_in_use | grep -q -v "\<${port_in}\>"
             then
-                echo "Error: No Viewer is listening on local port $port_in. Exiting."
+                echo "$(basename "$0"): No Viewer is listening on local port $port_in." >&2
                 exit 1
             fi
         fi
     elif [ -z "$port_in" ]
     then
-        echo "Error: Viewer host $host_in specified, but no port was supplied. Exiting."
+        echo "$(basename "$0"): Viewer host $host_in specified, but no port was supplied." >&2
         exit 1
     fi
     # TODO: Bounds check port number
 elif [ -n "$host_in" ]
 then
-    echo 'Error: -h (remove Viewer host) and -v (local Viewer) may not be combined. Exiting.'
+    echo "$(basename "$0"): -h (remove Viewer host) and -v (local Viewer) may not be combined." >&2
     exit 1
 else
     # Local Viewer requested
@@ -403,7 +385,7 @@ else
         fi
     elif list_ports_in_use | grep -q "\<${port_in}\>"
     then
-        echo "Error: Port $port_in is in use. Exiting."
+        echo "$(basename "$0"): Port $port_in is in use." >&2
         exit 1
     fi
 fi
@@ -417,7 +399,7 @@ if [ -n "$port_in" ]
 then
     port_cmd="-n $port_in"
 fi
-     
+
 # Run default debug
 if [ -z "$debug_cmd" ] && [ -z "$quiet" ] && [ -r "Debug.cfg" ]
 then
@@ -430,7 +412,7 @@ then
     checker
 fi
 
-#separate command-line from plexexec output
+# separate command-line from plexilexec output
 echo
 
 # Print summary if desired
@@ -441,11 +423,14 @@ fi
 
 if [ -n "$viewer" ]
 then
+    # *** FIXME ***
     # Launch the viewer, which will in turn invoke this script again with the automate flag
-    #echo "plexil -plexilexec $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $host_cmd $port_cmd $check $block $auto_run_cmd"
+    # The unquoted expansions are deliberate
+    # shellcheck disable=SC2086
     exec plexil -plexilexec $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $host_cmd $port_cmd $check $block $auto_run_cmd
 else
     # User doesn't want viewer
-    #echo "$prog $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $block"
+    # The unquoted expansions are deliberate
+    # shellcheck disable=SC2086
     exec "$prog" $plan_cmd $config_cmd $lib_dirs_cmd $lib_cmd $debug_cmd $block
 fi
