Resolved malformated -help option in plexilexec and plexiltest (needs testing on macOS), fixed 'can't shift that many' error for plexiltest -h

diff --git a/scripts/plexiltest b/scripts/plexiltest
--- a/scripts/plexiltest
+++ b/scripts/plexiltest
@@ -72,6 +72,15 @@ validate_file()
     fi
 }
 
+validate_host()
+{
+    if [ -z "$1" ]
+    then
+        echo "Error: missing host name for $2 option" >&2
+        usage
+        exit 2
+    fi
+}
 validNum()
 {
     if [ -z "$1" ]
@@ -137,8 +146,9 @@ summarize()
     echo
 }
 
-usage_text="Usage:\n\tplexiltest -p <plan> [-s <script file>] [-d <debug file>] [-L <library dir>]* [-l <library>]*\
- [-v [-h <hostname>] [-n <portnumber>] [-b]] [-ch] [-c <interface config>] \n"
+usage_text="Usage:
+        plexiltest -p <plan> [-s <script file>] [-d <debug file>] [-L <library dir>]* [-l <library>]* [-v [-h <hostname>] [-n <portnumber>] [-b]] [-ch] [-c <interface config>]
+"
 
 usage()
 {
@@ -146,39 +156,39 @@ usage()
     echo "For more options enter 'plexiltest -help'"
 }
 
-help_text="Options:\n\
-\n\
- -help \n\
-\t      displays this message\n\
- -p | -plan <plan> \n\
-\t      specify PLEXIL plan (required) \n\
- -s | -script <script> \n\
-\t      specifies a script file\n\
- -d | -debug <file name> \n\
-\t      debug file (default is Debug.cfg)\n\
- -L | -libraryPath <directory name>\n\
-\t      specifies a directory for finding plan library files\n\
- -q | -quiet \n\
-\t      Minimize output\n\
- -v | -viewer \n\
-\t      starts the Plexil Viewer\n\
- -h | -hostname <name> \n\
-\t      Name of remote host where Viewer is running\n\
- -n | -port <number> \n\
-\t      Port number to use for Viewer\n\
- -b | -blocking \n\
-\t      enables breakpoints in Viewer\n\
- -ch | -check \n\
-\t      runs the PLEXIL static checker prior to executing plan\n\
- -l | -library <file name>\n\
-\t      specifies a plan library (.plx file)\n\
- -? | -help \n\
-\t      shows this message of options
- -a | -autorun \n\
-\t  Runs the specified plan immediately at Viewer startup \n\
- --for-viewer \n\
-\t  Runs the exec with the supplied options, without checking them, and without starting the Viewer. \n\
-\t  Intended for use by the Plexil Viewer or other scripts."
+help_text="Options:
+
+ -help 
+	displays this message
+ -p | -plan <plan> 
+	specify PLEXIL plan (required) 
+ -s | -script <script> 
+	specifies a script file
+ -d | -debug <file name> 
+	debug file (default is Debug.cfg)
+ -L | -libraryPath <directory name>
+	specifies a directory for finding plan library files
+ -q | -quiet 
+	Minimize output
+ -v | -viewer 
+	starts the Plexil Viewer
+ -h | -hostname <name> 
+	Name of remote host where Viewer is running
+ -n | -port <number> 
+	Port number to use for Viewer
+ -b | -blocking 
+	enables breakpoints in Viewer
+ -ch | -check 
+	runs the PLEXIL static checker prior to executing plan
+ -l | -library <file name>
+	specifies a plan library (.plx file)
+ -? | -help 
+	shows this message of options
+ -a | -autorun 
+	Runs the specified plan immediately at Viewer startup 
+ --for-viewer 
+	Runs the exec with the supplied options, without checking them, and without starting the Viewer. 
+	Intended for use by the Plexil Viewer or other scripts."
 
 if [ -n "$PLEXIL_EXECUTABLE" ]
 then
@@ -236,6 +246,7 @@ do
 
         -h | -hostname )
             shift
+            validate_host "$1" "$save"
             host_in="-h $1";;       #viewer host name
         
         -help )
