plexilc, plexilisp scripts: Fix broken check for Emacs executable

diff --git a/scripts/plexilc b/scripts/plexilc
--- a/scripts/plexilc
+++ b/scripts/plexilc
@@ -211,6 +211,30 @@ plexilisp_compiler()
              --eval '(plexil)'
 }
 
+# Create the output filename for the file being compiled
+# $1: the file being compiled
+generate_output_fname()
+{
+    in_ext="$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')"
+    case "$in_ext" in
+        ple | pli | plp | epx )
+            echo "$1" | sed -e "s/$in_ext$/plx/"
+            ;;
+
+        pst )
+            echo "$1" | sed -e "s/$in_ext$/psx/"
+            ;;
+        * )
+            echo "Error: Unrecognized extension \"$in_ext\" for $(display_name "$1")" >&2
+            echo 'Supported extensions are: epx ple pli plp pst' >&2
+            if [ -n "${exit_on_fail}" ]
+            then
+                exit 1
+            fi
+            ;;
+    esac
+}
+
 # Compile a .pli file
 # $1: the file to compile
 # $2: Where to put the result
@@ -218,7 +242,7 @@ compile_plexilisp()
 {
     # Plexilisp plan/script
     EMACS="${EMACS-"$(command -v emacs)"}"
-    if [ -e "$EMACS" ]
+    if [ ! -x "$EMACS" ]
     then
         echo 'Fatal error: Emacs executable not found. Cannot compile Plexilisp.' >&2
         exit 1
