Fix various shell scripting gotchas, as identified by shellcheck
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-x@5197 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/plexilc b/scripts/plexilc
--- a/scripts/plexilc
+++ b/scripts/plexilc
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Generalized compiler driver for Plexil source files
 
-# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -77,29 +77,30 @@ check_env()
         echo to the full pathname of your 'plexil' or 'trunk' directory.
         exit 1
     fi
-    . ${PLEXIL_HOME}/scripts/plexil-setup.sh
+    # shellcheck source=plexil-setup.sh
+    . "${PLEXIL_HOME}/scripts/plexil-setup.sh"
 }
 
 generate_output_fname()
 {
     if [ -n "$output" ]
     then
-        echo $output
+        echo "$output"
         return
     fi
 
-    in_ext=`expr $1 : '.*\.\([a-z][a-z][a-z]\)$'`
+    in_ext=$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')
     case "$in_ext" in
         ( ple | pli | plp | epx )
-        echo $1 | sed -e "s/$in_ext$/plx/"
+        echo "$1" | sed -e "s/$in_ext$/plx/"
         ;;
 
         pst )
-            echo $1 | sed -e "s/$in_ext$/psx/"
+            echo "$1" | sed -e "s/$in_ext$/psx/"
             ;;
         * )
-            echo Unrecognized filename extension "$in_ext" for "$1" >&2
-            echo Supported extensions are: epx ple pli pst >&2
+            echo "Unrecognized filename extension $in_ext for $1" >&2
+            echo "Supported extensions are: epx ple pli pst" >&2
             exit 1
             ;;
     esac
@@ -114,24 +115,26 @@ compile_std_plexil()
         options="$options --debug" 
     fi
 
-    output=`generate_output_fname $1`
+    output=$(generate_output_fname "$1")
 
     if [ -n "$quiet" ]
     then
-        $plexil_compiler $options -o $output $1 > /dev/null 2>&1
+        # shellcheck disable=SC2086
+        $plexil_compiler $options -o "$output" "$1" > /dev/null 2>&1
     else 
-        $plexil_compiler $options -o $output $1
+        # shellcheck disable=SC2086
+        $plexil_compiler $options -o "$output" "$1"
     fi
     status=$?
     if [ $status -ne 0 ]
     then
-        echo Error: Standard Plexil compilation of $1 failed.
+        echo "Error: Standard Plexil compilation of $1 failed." >&2
         exit $status
     fi
 
     if [ -n "$check" ]
     then
-        $plexil_checker $output
+        "$plexil_checker" "$output"
     fi
 }
 
@@ -140,9 +143,9 @@ compile_plexilisp()
     # Plexilisp plan/script
     if [ -n "$quiet" ]
     then
-        emacs --batch --no-site-file --load $PLEXIL_HOME/compilers/plexilisp/plexil.el $1 --eval '(plexil)' > /dev/null 2>&1
+        emacs --batch --no-site-file --load "$PLEXIL_HOME/compilers/plexilisp/plexil.el" "$1" --eval '(plexil)' > /dev/null 2>&1
     else
-        emacs --batch --no-site-file --load $PLEXIL_HOME/compilers/plexilisp/plexil.el $1 --eval '(plexil)'
+        emacs --batch --no-site-file --load "$PLEXIL_HOME/compilers/plexilisp/plexil.el" "$1" --eval '(plexil)'
     fi
 
     if [ -n "$output" ]
@@ -152,40 +155,40 @@ compile_plexilisp()
     fi
 
     # If plexilisp generates a plan, we can check it.
-    output=`generate_output_fname $1`
-    if [ -r $output -a -n "$check" ]
+    output=$(generate_output_fname "$1")
+    if [ -r "$output" ] && [ -n "$check" ]
     then
-        $plexil_checker $output
+        "$plexil_checker" "$output"
     fi
 }
 
 compile_ext_plexil()
 {
     # Extended Plexil XML plan
-    output=`generate_output_fname $1`
-    $PLEXIL_HOME/scripts/eplexil $1 $output
+    output=$(generate_output_fname "$1")
+    "$PLEXIL_HOME/scripts/eplexil" "$1" "$output"
     status=$?
     if [ $status -ne 0 ]
     then
-        echo Error: Extended Plexil translation of $1 failed.
+        echo "Error: Extended Plexil translation of $1 failed." >&2
         exit $status
     fi
 
     if [ -n "$check" ]
     then
-        $plexil_checker $output
+        "$plexil_checker" "$output"
     fi
 }
 
 compile_plexilscript()
 {
     # Plexilscript
-    output=`generate_output_fname $1`
-    $plexilscript_compiler < $1 > $output
+    output=$(generate_output_fname "$1")
+    $plexilscript_compiler < "$1" > "$output"
     status=$?
     if [ $status -ne 0 ]
     then
-        echo Error: compilation of $1 failed.
+        echo "Error: compilation of $1 failed." >&2
         exit $status
     fi
 }
@@ -193,12 +196,13 @@ compile_plexilscript()
 compile_plp()
 {
     # Standard Plexil w/ preprocessing
-    ple_fname=`echo "$1" | sed -e 's|.plp$|.ple|'`
-    ${PLEXIL_HOME}/scripts/plexilpp $pp_args -o "$ple_fname" "$1"
+    ple_fname=$(echo "$1" | sed -e 's|.plp$|.ple|')
+    # shellcheck disable=SC2086
+    "${PLEXIL_HOME}/scripts/plexilpp" $pp_args -o "$ple_fname" "$1"
     status=$?
     if [ $status -ne 0 ]
     then
-        echo Error: Preprocessing of $1 failed.
+        echo "Error: Preprocessing of $1 failed." >&2
         exit $status
     fi
 
@@ -248,7 +252,7 @@ do
 
         ( -v | -version )
         echo 'plexilc script version 1.2'
-        $plexil_compiler --version
+        "$plexil_compiler" --version
         exit 0
         ;;
 
@@ -268,20 +272,20 @@ then
     exit 1
 fi
 
-if [ ! -r $1 ]
+if [ ! -r "$1" ]
 then
-    echo "Error: file $1 does not exist or is not readable"
+    echo "Error: file $1 does not exist or is not readable" >&2
     exit 1
 fi
 
 check_env
 
-JARS_DIR=${PLEXIL_HOME}/jars
+JARS_DIR="${PLEXIL_HOME}/jars"
 ANTLR_RUNTIME_JAR=antlr-3.5.2-complete-no-st3.jar
 JAVA=java
 if [ -n "$JAVA_HOME" ]
 then
-    JAVA=$JAVA_HOME/bin/java
+    JAVA="$JAVA_HOME/bin/java"
 fi
 
 # Commands to execute
@@ -290,31 +294,31 @@ plexilscript_compiler="$JAVA -cp ${JARS_DIR}/plexilscript.jar:${JARS_DIR}/antlr.
 plexil_checker="$PLEXIL_HOME/scripts/checkDecls"
 
 # Select translator for this file based on extension
-in_ext=`expr $1 : '.*\.\([a-z][a-z][a-z]\)$'`
+in_ext=$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')
 
 case $in_ext in
     epx )
-        compile_ext_plexil $1
+        compile_ext_plexil "$1"
         ;;
     
     ple )
-        compile_std_plexil $1
+        compile_std_plexil "$1"
         ;;
     
     plp )
-        compile_plp $1
+        compile_plp "$1"
         ;;
     
     pli )
-        compile_plexilisp $1
+        compile_plexilisp "$1"
         ;;
 
     pst )
-        compile_plexilscript $1
+        compile_plexilscript "$1"
         ;;
 
     * )
-        echo Unable to select compiler for "$1"
+        echo "Unable to select compiler for $1" >&2
         usage
         exit 1
         ;;
diff --git a/scripts/run-agents b/scripts/run-agents
--- a/scripts/run-agents
+++ b/scripts/run-agents
@@ -2,7 +2,7 @@
 # File: $SVNROOT/scripts/run-agents
 # Note: Script to run two Plexil agent systems using IPC
 
-# Copyright (c) 2006-2019, Universities Space Research Association (USRA).
+# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -33,14 +33,14 @@ usage ()
 {
 cat <<EOF
 
-Usage:      `basename $0` [options] <agent1> [-c <config>] [-l <lib>] [-L <lib_dir>] <agent2> [-c <config>] [-l <lib>] [-L <lib_dir>]
+Usage:      $(basename "$0") [options] <agent1> [-c <config>] [-l <lib>] [-L <lib_dir>] <agent2> [-c <config>] [-l <lib>] [-L <lib_dir>]
 
 Options:    -v -viewer  := start the Plexil Viewer
             -x -xterms  := run the execs in xterms (if your system has them)
             -i -ipc     := run IPC in an xterm (rather than in the background)
             -n -no-ipc  := do not run IPC at all
 
-Examples:   `basename $0` -x sim cmd -l get-int -l get-real
+Examples:   $(basename "$0") -x sim cmd -l get-int -l get-real
 
 Notes:      <agent1> and <agent2> are the "base names" of the plans, e.g., "cmd" for cmd.pli
             or "t1-sim" for t1-sim.pli.
@@ -54,19 +54,28 @@ exit
 }
 
 # Check for something like the right parameters and/or a "help" request
-if [ $# -lt 2 ] ; then usage ; fi
+if [ $# -lt 2 ]
+then
+    usage
+fi
 
 # Check for PLEXIL_HOME being set (correctly, one hopes)
-if [ -z "$PLEXIL_HOME" ] ; then echo "PLEXIL_HOME is not set" ; exit ; fi
-if [ ! -e $PLEXIL_HOME/makeinclude/generic-plexil.make ] ; then
+if [ -z "$PLEXIL_HOME" ]
+then
+    echo "PLEXIL_HOME is not set"
+    exit 1
+fi
+if [ ! -e "$PLEXIL_HOME/makeinclude/generic-plexil.make" ]
+then
     echo "PLEXIL_HOME is set to $PLEXIL_HOME, but I can't find some required files."
 fi
 
 # Check for xterms and IPC/central
-has_xterm=`which xterm`
+has_xterm="$(command -v xterm)"
 use_xterm=no
 use_viewer=no
-ipc_running=`ps aux | egrep "ipc|central" | grep -v grep`
+# shellcheck disable=SC2009
+ipc_running="$(ps aux | grep -E "ipc|central" | grep -v grep)"
 run_ipc_in_background=yes
 ipc_pid=
 no_ipc=
@@ -77,147 +86,146 @@ do
     # TODO: use case statement
     if [ "$1" = "-h" ] || [ "$1" = "-help" ]
     then
-	usage
-	exit 0
+	    usage
+	    exit 0
     fi
     if [ "$1" = "-d" ]
     then
-	debug=true
-	shift
+	    debug=true
+	    shift
     elif [ "$1" = "-v" ] || [ "$1" = "-viewer" ]
     then
-	use_viewer=yes
-	shift
+	    use_viewer=yes
+	    shift
     elif [ "$1" = "-x" ] || [ "$1" = "-xterm" ] || [ "$1" = "-xterms" ]
     then
-	use_xterm=yes
-	shift
+	    use_xterm=yes
+	    shift
     elif [ "$1" = "-vx" ] || [ "$1" = "-xv" ]
     then
-	use_xterm=yes
-	use_viewer=yes
-	shift
+	    use_xterm=yes
+	    use_viewer=yes
+	    shift
     elif [ "$1" = "-i" ] || [ "$1" = "-ipc" ]
     then
-	run_ipc_in_background=no
-	shift
+	    run_ipc_in_background=no
+	    shift
     elif [ "$1" = "-n" ] || [ "$1" = "-no-ipc" ]
     then
-	no_ipc=yes
-	shift
+	    no_ipc=yes
+	    shift
     elif [ "$1" = "-c" ] 
     then
-        if [ -z $com1 ]
-	then
-	    shift
-	    com1=$1
-	    shift;
+        if [ -z "$com1" ]
+	    then
+	        shift
+	        com1="$1"
+	        shift;
         else
-	    shift
-	    com2=$1
-	    shift
+	        shift
+	        com2="$1"
+	        shift
         fi
     elif [ "$1" = "-l" ]
     then
-        if [ -z $agent2_raw ]
-	then
-	    shift
-	    libs1="$libs1$1 "
-	    shift
+        if [ -z "$agent2_raw" ]
+	    then
+	        shift
+	        libs1="$libs1$1 "
+	        shift
         else
-	    shift
-	    libs2="$libs2$1 "
-	    shift
+	        shift
+	        libs2="$libs2$1 "
+	        shift
         fi
     elif [ "$1" = "-L" ]
     then
-        if [ -z $agent2_raw ]
-	then
-	    libdirs1="$libdirs1$1 $2 "
-	    shift 2
+        if [ -z "$agent2_raw" ]
+	    then
+	        libdirs1="$libdirs1$1 $2 "
+	        shift 2
         else
-	    libdirs2="$libdirs1$1 $2 "
-	    shift 2
+	        libdirs2="$libdirs1$1 $2 "
+	        shift 2
         fi
     else
-        if [ -z $agent1_raw ]
-	then
-	    agent1_raw=$1
-	    shift
-        elif [ -z $agent2_raw ]
-	then
-	    agent2_raw=$1
-	    shift
+        if [ -z "$agent1_raw" ]
+	    then
+	        agent1_raw="$1"
+	        shift
+        elif [ -z "$agent2_raw" ]
+	    then
+	        agent2_raw="$1"
+	        shift
         else
-	    echo "The \"$1\" parameter is ambiguous.  Maybe it is a library missing the -l flag?"
-	    usage
-	    exit 1
+	        echo "The \"$1\" parameter is ambiguous.  Maybe it is a library missing the -l flag?"
+	        usage
         fi
     fi
 done
 
-if [ -z $agent1_raw ] || [ -z $agent2_raw ] ; then
+if [ -z "$agent1_raw" ] || [ -z "$agent2_raw" ] ; then
   echo "Two agents required"
   usage
 fi
 
 # Allow for either base names or names including extensions
-agent1=`echo $agent1_raw | awk '{ split($0, arr, "."); print(arr[1]) }'`
-agent2=`echo $agent2_raw | awk '{ split($0, arr, "."); print(arr[1]) }'`
+agent1="$(echo "$agent1_raw" | awk '{ split($0, arr, "."); print(arr[1]) }')"
+agent2="$(echo "$agent2_raw" | awk '{ split($0, arr, "."); print(arr[1]) }')"
 
 # Guess at what the communications configurations might be for these agents
 # t1-cmd = cmd.xml or t1-cmd.xml = cmd-t1; cmd = cmd.xml
-if [ -z $com1 ] ;
+if [ -z "$com1" ]
 then
-    if [ -e $agent1.xml ] ;
+    if [ -e "$agent1.xml" ]
     then
-        com1=$agent1.xml ;
-    elif [ -e `echo $agent1 | awk '{ split($0, arr, "-"); print(arr[1]) }'`.xml ] ;
+        com1="$agent1.xml"
+    elif [ -e "$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml" ]
     then
-        com1=`echo $agent1 | awk '{ split($0, arr, "-"); print(arr[1]) }'`.xml
-    elif [ -e `echo $agent1 | awk '{ split($0, arr, "-"); print(arr[2]) }'`.xml ] ;
+        com1="$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml"
+    elif [ -e "$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml" ]
     then
-        com1=`echo $agent1 | awk '{ split($0, arr, "-"); print(arr[2]) }'`.xml
+        com1="$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml"
     else
         echo "No communications configuration file found for base name $agent1"
-        exit
+        exit 1
     fi
 fi
 
 # And now for agent2
-if [ -z $com2 ] ;
+if [ -z "$com2" ]
 then
-    if [ -e $agent2.xml ] ;
+    if [ -e "$agent2.xml" ]
     then
-        com2=$agent2.xml ;
-    elif [ -e `echo $agent2 | awk '{ split($0, arr, "-"); print(arr[1]) }'`.xml ] ;
+        com2="$agent2.xml"
+    elif [ -e "$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml" ]
     then
-        com2=`echo $agent2 | awk '{ split($0, arr, "-"); print(arr[1]) }'`.xml
-    elif [ -e `echo $agent2 | awk '{ split($0, arr, "-"); print(arr[2]) }'`.xml ] ;
+        com2="$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml"
+    elif [ -e "$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml" ]
     then
-        com2=`echo $agent2 | awk '{ split($0, arr, "-"); print(arr[2]) }'`.xml
+        com2="$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml"
     else
         echo "No communications configuration file found for base name $agent2"
-        exit
+        exit 1
     fi
 fi
 
 # Now, double check to be sure we have comm configuration files
-if [ ! -e $com1 ] ; then
-    if [ ! -e $com1.xml ] ; then
+if [ ! -e "$com1" ] ; then
+    if [ ! -e "$com1.xml" ] ; then
         echo " " ; echo "No communications configuration file found for \"-c $com1\""
         usage
     else
-        com1=$com1.xml
+        com1="$com1.xml"
     fi
 fi
 # Now, do it again for the second agent
-if [ ! -e $com2 ] ; then
-    if [ ! -e $com2.xml ] ; then
+if [ ! -e "$com2" ] ; then
+    if [ ! -e "$com2.xml" ] ; then
         echo " " ; echo "No communications configuration file found for \"-c $com2\""
         usage
     else
-        com2=$com2.xml
+        com2="$com2.xml"
     fi
 fi
 
@@ -225,29 +233,29 @@ fi
 echo " "
 
 # Try to figure out which make to use
-MAKE=make
-if [ `uname -s` = 'FreeBSD' ]
+MAKE='make'
+if [ "$(uname -s)" = 'FreeBSD' ]
 then
-    if ( which gmake )
+    if ( command -v gmake )
     then
-	MAKE=gmake
+	    MAKE='gmake'
     else
-	echo 'ERROR: GNU make not found. Please install it.'
-	exit 1
+	    echo 'ERROR: GNU make not found. Please install it.'
+	    exit 1
     fi
 fi
 
 # Try to figure out which makefile to use
-if [ -e "makefile" ] ; then
-    make_file=makefile
-elif [ -e "Makefile" ] ; then
-    make_file=Makefile
+if [ -e 'makefile' ] ; then
+    make_file='makefile'
+elif [ -e 'Makefile' ] ; then
+    make_file='Makefile'
 else
-    make_file=$PLEXIL_HOME/makeinclude/generic-plexil.make
+    make_file="$PLEXIL_HOME/makeinclude/generic-plexil.make"
 fi
 
 # Keep the plans up-to-date if possible...
-${MAKE} -f $make_file $agent1.plx $agent2.plx
+"${MAKE}" -f "$make_file" "$agent1.plx" "$agent2.plx"
 make_status=$?
 # bail if things don't compile properly
 if [ $make_status != 0 ] ;
@@ -259,29 +267,48 @@ fi
 # Set up the libraries for inclusion
 for lib in $libs1 ;
 do
-    lib=`echo $lib | awk '{ split($0, arr, "."); print(arr[1]) }'`
+    lib="$(echo "$lib" | awk '{ split($0, arr, "."); print(arr[1]) }')"
     # allow for both lib/name and just name
-    if [ ! -e $lib.pli ] ; then
-        if [ -e lib/$lib.pli ] ; then lib=lib/$lib ;
-        else echo "$lib.pli not found" ; exit ;
+    if [ ! -e "$lib.pli" ]
+    then
+        if [ -e "lib/$lib.pli" ]
+        then
+            lib="lib/$lib"
+        else
+            echo "$lib.pli not found"
+            exit
         fi
     fi
-    ${MAKE} $lib.plx
+    ${MAKE} "$lib.plx"
     # stop of the compile fails
-    if [ $? != 0 ] ; then echo "Error: $lib.plx failed to compile" ; exit ; fi
+    if [ $? != 0 ]
+    then
+        echo "Error: $lib.plx failed to compile"
+        exit
+    fi
     libraries1="$libraries1 -l $lib.plx"
 done
+
 # And again for the second agent
 for lib in $libs2 ;
 do
-    lib=`echo $lib | awk '{ split($0, arr, "."); print(arr[1]) }'`
-    if [ ! -e $lib.pli ] ; then
-        if [ -e lib/$lib.pli ] ; then lib=lib/$lib ;
-        else echo "$lib.pli not found" ; exit ;
+    lib="$(echo "$lib" | awk '{ split($0, arr, "."); print(arr[1]) }')"
+    if [ ! -e "$lib.pli" ]
+    then
+        if [ -e "lib/$lib.pli" ]
+        then
+            lib="lib/$lib"
+        else
+            echo "$lib.pli not found"
+            exit 1
         fi
     fi
-    ${MAKE} $lib.plx
-    if [ $? != 0 ] ; then echo "Error: $lib.plx failed to compile" ; exit ; fi
+    ${MAKE} "$lib.plx"
+    if [ $? != 0 ]
+    then
+        echo "Error: $lib.plx failed to compile"
+        exit 1
+    fi
     libraries2="$libraries2 -l $lib.plx"
 done
 
@@ -291,7 +318,7 @@ if [ "$use_viewer" = "yes" ] ;
 then
     cmd1="plexilexec -v -b -p $agent1.plx -c $com1 $libdirs1 $libraries1"
     cmd2="plexilexec -v -b -p $agent2.plx -c $com2 $libdirs2 $libraries2"
-    if [ "`uname`" = "Darwin" ] ;
+    if [ "$(uname)" = 'Darwin' ] ;
     then
         sleep_time=15
     else
@@ -303,22 +330,27 @@ else
     sleep_time=1
 fi
 
-if [ ! -z $debug ] ;
+if [ -n "$debug" ]
 then
-    echo " " ; echo "agent1_raw:  " $agent1_raw
-    echo "agent1:      " $agent1
-    echo "com1:        " $com1
-    echo "libs1:       " $libs1
-    echo "libraries1:  " $libraries1
-    echo " " ; echo "agent2_raw:  " $agent2_raw
-    echo "agent2:      " $agent2
-    echo "com2:        " $com2
-    echo "libs2:       " $libs2
-    echo "libraries2:  " $libraries2
-    echo " " ; echo "cmd1:        " $cmd1
-    echo "cmd2:        " $cmd2
-    echo " " ; echo "PLEXIL_HOME: " $PLEXIL_HOME
-    echo "make_file:   " $make_file ; echo " "
+    echo " " 
+    echo "agent1_raw:   $agent1_raw"
+    echo "agent1:       $agent1"
+    echo "com1:         $com1"
+    echo "libs1:        $libs1"
+    echo "libraries1:   $libraries1"
+    echo " " 
+    echo "agent2_raw:   $agent2_raw"
+    echo "agent2:       $agent2"
+    echo "com2:         $com2"
+    echo "libs2:        $libs2"
+    echo "libraries2:   $libraries2"
+    echo " " 
+    echo "cmd1:         $cmd1"
+    echo "cmd2:         $cmd2"
+    echo " "
+    echo "PLEXIL_HOME:  $PLEXIL_HOME"
+    echo "make_file:    $make_file"
+    echo " "
     exit
 fi
 
@@ -330,7 +362,7 @@ then
     then
         echo "ipc (central) must already be running for this script to work without xterm..."
         echo " "
-        exit
+        exit 1
     else
         echo "xterm not found: both agents will be run in the background..."
         echo " "
@@ -344,7 +376,8 @@ then
     then
         echo ' '
         echo "Starting IPC..."
-        if [ "$run_ipc_in_background" = "no" ] ; then
+        if [ "$run_ipc_in_background" = "no" ]
+        then
             xterm -g 172x20 -T "IPC" ipc &
         else
             central -s -L -f/dev/null &
