Backport plexil-6 improvements to shell scripts
git-svn-id: https://svn.code.sf.net/p/plexil/code/branches/plexil-4@5358 d2be67b0-814c-0410-949f-d215b6b29573

diff --git a/scripts/plexilc b/scripts/plexilc
--- a/scripts/plexilc
+++ b/scripts/plexilc
@@ -100,10 +100,28 @@ generate_output_fname()
             ;;
         * )
             echo "Unrecognized filename extension \"$in_ext\" for $1" >&2
-            echo 'Supported extensions are: epx ple pli pst' >&2
+            echo 'Supported extensions are: epx ple pli plp pst' >&2
             exit 1
             ;;
     esac
+}
+
+check_env
+
+JARS_DIR="$PLEXIL_HOME"/jars
+ANTLR_RUNTIME_JAR=antlr-3.5.2-complete-no-st3.jar
+JAVA=java
+if [ -n "$JAVA_HOME" ]
+then
+    JAVA="$JAVA_HOME"/bin/java
+fi
+
+# Commands to execute
+plexil_checker="$PLEXIL_HOME/scripts/checkDecls"
+
+std_plexil_compiler()
+{
+    "$JAVA" -classpath "$JARS_DIR/PlexilCompiler.jar:$JARS_DIR/$ANTLR_RUNTIME_JAR:$JARS_DIR/nanoxml.jar:$JARS_DIR/saxon.jar" plexil.Compiler "$@"
 }
 
 compile_std_plexil()
@@ -120,10 +138,10 @@ compile_std_plexil()
     if [ -n "$quiet" ]
     then
         # shellcheck disable=SC2086
-        "$plexil_compiler" $options -o "$output" "$1" > /dev/null 2>&1
+        std_plexil_compiler $options -o "$output" "$1" > /dev/null 2>&1
     else 
         # shellcheck disable=SC2086
-        "$plexil_compiler" $options -o "$output" "$1"
+        std_plexil_compiler $options -o "$output" "$1"
     fi
     status=$?
     if [ $status -ne 0 ]
@@ -183,8 +201,8 @@ compile_ext_plexil()
 compile_plexilscript()
 {
     # Plexilscript
-    output="$(generate_output_fname "$1")"
-    "$plexilscript_compiler" < "$1" > "$output"
+    output=$(generate_output_fname "$1")
+    "$JAVA" -classpath "$JARS_DIR/plexilscript.jar:$JARS_DIR/antlr.jar" plexilscript.PlexilScriptParse < "$1" > "$output"
     status=$?
     if [ $status -ne 0 ]
     then
@@ -196,9 +214,9 @@ compile_plexilscript()
 compile_plp()
 {
     # Standard Plexil w/ preprocessing
-    ple_fname="$(echo "$1" | sed -e 's|.plp$|.ple|')" 
+    ple_fname="$(echo "$1" | sed -e 's|.plp$|.ple|')"
     # shellcheck disable=SC2086
-   "$PLEXIL_HOME"/scripts/plexilpp $pp_args -o "$ple_fname" "$1"
+    "$PLEXIL_HOME"/scripts/plexilpp $pp_args -o "$ple_fname" "$1"
     status=$?
     if [ $status -ne 0 ]
     then
@@ -207,7 +225,20 @@ compile_plp()
     fi
 
     compile_std_plexil "$ple_fname"
-    # TODO: delete ple_fname??
+    status=$?
+
+    if [ $status -ne 0 ]
+    then
+        # Don't delete preprocessor output file in case
+        # the error is a result of a macro goof.
+        echo "Error: Compilation of $1 failed." >&2
+        exit $status
+    fi
+
+    # Delete preprocessor output file
+    /bin/rm -f "$ple_fname"
+
+    return 0
 }
 
 # Parse options
@@ -252,7 +283,7 @@ do
 
         ( -v | -version )
         echo 'plexilc script version 1.2'
-        "$plexil_compiler" --version
+        std_plexil_compiler --version
         exit 0
         ;;
 
@@ -277,21 +308,6 @@ then
     echo "Error: file $1 does not exist or is not readable" >&2
     exit 1
 fi
-
-check_env
-
-JARS_DIR="$PLEXIL_HOME"/jars
-ANTLR_RUNTIME_JAR=antlr-3.5.2-complete-no-st3.jar
-JAVA=java
-if [ -n "$JAVA_HOME" ]
-then
-    JAVA="$JAVA_HOME"/bin/java
-fi
-
-# Commands to execute
-plexil_compiler="$JAVA -classpath $JARS_DIR/PlexilCompiler.jar:$JARS_DIR/$ANTLR_RUNTIME_JAR:$JARS_DIR/nanoxml.jar:$JARS_DIR/saxon.jar plexil.Compiler"
-plexilscript_compiler="$JAVA -cp ${JARS_DIR}/plexilscript.jar:${JARS_DIR}/antlr.jar plexilscript.PlexilScriptParse"
-plexil_checker="$PLEXIL_HOME/scripts/checkDecls"
 
 # Select translator for this file based on extension
 in_ext="$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')"
