Add support for multiple files to plexilc and new option to halt compilation on file failure.

diff --git a/scripts/plexilc b/scripts/plexilc
--- a/scripts/plexilc
+++ b/scripts/plexilc
@@ -45,8 +45,8 @@
 
 usage ()
 {
-    echo "Usage: $(basename "$0") [options] <source-file>"
-    echo ' Compile a Plexil plan or simulator script to XML'
+    echo "Usage: $(basename "$0") [options] file..."
+    echo ' Compile Plexil plans or simulator scripts to XML'
     echo 'Options:'
     echo '  -h, -help, --help       Print this help and exit'
     echo '  -v, -version            Print translator version and exit'
@@ -59,6 +59,8 @@ usage ()
     echo '  -q, -quiet              Parse files quietly'
     echo '  -I <directory>          Include directory'
     echo '                          (.plp files only)'
+    echo '  -e, -exit-on-failure    If compillation of any file fails, exit'
+    echo '                          immediately'
     echo 'Not all options are supported for all file formats.'
     echo
     echo 'Recognized extensions are:'
@@ -118,7 +120,10 @@ generate_output_fname()
         * )
             echo "Error: Unrecognized filename extension \"$in_ext\" for $1" >&2
             echo 'Supported extensions are: epx ple pli plp pst' >&2
-            exit 1
+            if [ -n "${exit_on_fail}" ]
+            then
+                exit 1
+            fi
             ;;
     esac
 }
@@ -141,7 +146,10 @@ compile_std_plexil()
     if [ $status -ne 0 ]
     then
         echo "Error: Standard Plexil compilation of $1 failed." >&2
-        exit $status
+        if [ -n "${exit_on_fail}" ]
+        then
+            exit $status
+        fi
     fi
 }
 
@@ -151,7 +159,10 @@ plexilisp_compiler()
     if [ -z "$EMACS" ]
     then
         echo 'Error: emacs not found. Cannot compile Plexilisp.' >&2
-        exit 1
+        if [ -n "${exit_on_fail}" ]
+        then
+            exit 1
+        fi
     fi
     "$EMACS" --batch --no-site-file --load "$PLEXIL_HOME"/compilers/plexilisp/plexil.el "$1" --eval '(plexil)'
 }
@@ -172,7 +183,10 @@ compile_plexilisp()
     if [ ! -r "$actual_output" ]
     then
         echo "Error: Plexilisp translation of $1 failed." >&2
-        exit 1
+        if [ -n "${exit_on_fail}" ]
+        then
+            exit 1
+        fi
     fi
 
     if [ "$output" != "$actual_output" ]
@@ -193,7 +207,10 @@ compile_ext_plexil()
     if [ $status -ne 0 ]
     then
         echo "Error: Extended Plexil translation of $1 failed." >&2
-        exit $status
+        if [ -n "${exit_on_fail}" ]
+        then
+            exit $status
+        fi
     fi
 }
 
@@ -205,7 +222,10 @@ compile_plexilscript()
     if [ $status -ne 0 ]
     then
         echo "Error: compilation of $1 failed." >&2
-        exit $status
+        if [ -n "${exit_on_fail}" ]
+        then
+            exit $status
+        fi
     fi
 }
 
@@ -219,7 +239,10 @@ compile_plp()
     if [ $status -ne 0 ]
     then
         echo "Error: Preprocessing of $1 failed." >&2
-        exit $status
+        if [ -n "${exit_on_fail}" ]
+        then
+            exit $status
+        fi
     fi
 
     # Exits if error detected
@@ -229,6 +252,59 @@ compile_plp()
     /bin/rm -f "$ple_fname"
 
     return 0
+}
+
+compile_argument()
+{
+    if [ ! -r "$1" ]
+    then
+        echo "Error: file $1 does not exist or is not readable" >&2
+        if [ -n "${exit_on_fail}" ]
+        then
+            exit 1
+        fi
+    fi
+
+    output="${output:-"$(generate_output_fname "$1")"}"
+
+    # Select translator for this file based on extension
+    in_ext="$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')"
+
+    case "$in_ext" in
+        epx )
+            compile_ext_plexil "$1"
+            ;;
+        
+        ple )
+            compile_std_plexil "$1"
+            ;;
+        
+        pli )
+            compile_plexilisp "$1"
+            ;;
+        
+        plp )
+            compile_plp "$1"
+            ;;
+
+        pst )
+            compile_plexilscript "$1"
+            ;;
+
+        * )
+            echo "Unable to select compiler for $1" >&2
+            usage
+            if [ -n "${exit_on_fail}" ]
+            then
+                exit 2
+            fi
+            ;;
+    esac
+
+    if [ -n "$check" ] && [ "$in_ext" != "pst" ] && [ -r "$output" ]
+    then
+        $plexil_checker "$output"
+    fi
 }
 
 # Parse options
@@ -272,9 +348,14 @@ do
         ;;
 
         ( -v | -version )
-        echo 'plexilc script version 1.2'
+        echo 'plexilc script version 1.3'
         std_plexil_compiler --version
         exit 0
+        ;;
+
+        (-e | -exit-on-failiure )
+        exit_on_fail="$1"
+        shift
         ;;
 
         *)
@@ -288,53 +369,20 @@ done
 # If we got this far, we are expecting a filename to translate
 if [ $# -lt 1 ]
 then
-    echo "Error: no filename supplied."
+    echo "Error: no filename supplied." >&2
     usage
     exit 2
 fi
 
-if [ ! -r "$1" ]
-then
-    echo "Error: file $1 does not exist or is not readable" >&2
-    exit 1
-fi
-
-output="${output:-"$(generate_output_fname "$1")"}"
-
-# Select translator for this file based on extension
-in_ext="$(expr "$1" : '.*\.\([a-z][a-z][a-z]\)$')"
-
-case "$in_ext" in
-    epx )
-        compile_ext_plexil "$1"
-        ;;
-    
-    ple )
-        compile_std_plexil "$1"
-        ;;
-    
-    pli )
-        compile_plexilisp "$1"
-        ;;
-    
-    plp )
-        compile_plp "$1"
-        ;;
-
-    pst )
-        compile_plexilscript "$1"
-        ;;
-
-    * )
-        echo "Unable to select compiler for $1" >&2
-        usage
-        exit 2
-        ;;
-esac
-
-if [ -n "$check" ] && [ "$in_ext" != "pst" ] && [ -r "$output" ]
-then
-    $plexil_checker "$output"
-fi
+# Once we have read the options and know that we have files we can compile each of them sequentialy
+while [ $#  -gt 0 ]
+do
+    if [ ! -n "$quiet" ]
+    then
+        echo "Compiling file: $1"
+    fi
+    compile_argument "$1"
+    shift
+done
 
 exit 0
