First round of cleanup for run-agents

diff --git a/scripts/run-agents b/scripts/run-agents
--- a/scripts/run-agents
+++ b/scripts/run-agents
@@ -31,7 +31,7 @@ debug=
 
 usage ()
 {
-cat <<EOF
+cat >&2 <<EOF
 
 Usage:      $(basename "$0") [options] <agent1> [-c <config>] [-l <lib>] [-L <lib_dir>] <agent2> [-c <config>] [-l <lib>] [-L <lib_dir>]
 
@@ -50,32 +50,24 @@ Notes:      <agent1> and <agent2> are the "base names" of the plans, e.g., "cmd"
             will be tried.
 
 EOF
-exit
 }
 
 # Check for something like the right parameters and/or a "help" request
-if [ $# -lt 2 ]
-then
-    usage
-fi
+if [ $# -lt 2 ] ; then usage ; exit 2 ; fi
 
 # Check for PLEXIL_HOME being set (correctly, one hopes)
-if [ -z "$PLEXIL_HOME" ]
-then
-    echo "PLEXIL_HOME is not set"
-    exit 1
-fi
-if [ ! -e "$PLEXIL_HOME/makeinclude/generic-plexil.make" ]
-then
+if [ -z "$PLEXIL_HOME" ] ; then echo 'PLEXIL_HOME is not set' ; exit 2 ; fi
+if [ ! -e "$PLEXIL_HOME/makeinclude/generic-plexil.make" ] ; then
     echo "PLEXIL_HOME is set to $PLEXIL_HOME, but I can't find some required files."
 fi
 
-# Check for xterms and IPC/central
+# Check for xterm and IPC/central
 has_xterm="$(command -v xterm)"
 use_xterm=no
 use_viewer=no
 # shellcheck disable=SC2009
-ipc_running="$(ps aux | grep -E "ipc|central" | grep -v grep)"
+# pgrep isn't part of POSIX standard
+ipc_running="$(ps aux | grep -E 'ipc|central' | grep -v grep)"
 run_ipc_in_background=yes
 ipc_pid=
 no_ipc=
@@ -117,22 +109,22 @@ do
     elif [ "$1" = "-c" ] 
     then
         if [ -z "$com1" ]
-	    then
-	        shift
-	        com1="$1"
-	        shift;
+	then
+	    shift
+	    com1="$1"
+	    shift;
         else
-	        shift
-	        com2="$1"
-	        shift
+	    shift
+	    com2="$1"
+	    shift
         fi
     elif [ "$1" = "-l" ]
     then
         if [ -z "$agent2_raw" ]
-	    then
-	        shift
-	        libs1="$libs1$1 "
-	        shift
+	then
+	    shift
+	    libs1="$libs1$1 "
+	    shift
         else
 	        shift
 	        libs2="$libs2$1 "
@@ -141,25 +133,26 @@ do
     elif [ "$1" = "-L" ]
     then
         if [ -z "$agent2_raw" ]
-	    then
-	        libdirs1="$libdirs1$1 $2 "
-	        shift 2
+	then
+	    libdirs1="$libdirs1$1 $2 "
+	    shift 2
         else
 	        libdirs2="$libdirs1$1 $2 "
 	        shift 2
         fi
     else
         if [ -z "$agent1_raw" ]
-	    then
-	        agent1_raw="$1"
-	        shift
+	then
+	    agent1_raw="$1"
+	    shift
         elif [ -z "$agent2_raw" ]
-	    then
-	        agent2_raw="$1"
-	        shift
+	then
+	    agent2_raw="$1"
+	    shift
         else
-	        echo "The \"$1\" parameter is ambiguous.  Maybe it is a library missing the -l flag?"
-	        usage
+	    echo "The \"$1\" parameter is ambiguous.  Maybe it is a library missing the -l flag?"
+	    usage
+	    exit 2
         fi
     fi
 done
@@ -167,25 +160,41 @@ done
 if [ -z "$agent1_raw" ] || [ -z "$agent2_raw" ] ; then
   echo "Two agents required"
   usage
+  exit 2
 fi
 
 # Allow for either base names or names including extensions
-agent1="$(echo "$agent1_raw" | awk '{ split($0, arr, "."); print(arr[1]) }')"
-agent2="$(echo "$agent2_raw" | awk '{ split($0, arr, "."); print(arr[1]) }')"
+agent_name()
+{
+    printf '%s\n' "$1" | awk '{ split($0, arr, "."); print(arr[1]) }'
+}
+
+agent1="$(agent_name "$agent1_raw")"
+agent2="$(agent_name "$agent2_raw")"
+
+before_dash()
+{
+    printf '%s\n' "$1" | awk '{ split($0, arr, "-"); print(arr[1]) }'
+}
+
+after_dash()
+{
+    printf '%s\n' "$1" | awk '{ split($0, arr, "-"); print(arr[1]) }'
+}
 
 # Guess at what the communications configurations might be for these agents
 # t1-cmd = cmd.xml or t1-cmd.xml = cmd-t1; cmd = cmd.xml
-if [ -z "$com1" ]
+if [ -z "$com1" ] ;
 then
-    if [ -e "$agent1.xml" ]
+    if [ -e "$agent1.xml" ] ;
     then
-        com1="$agent1.xml"
-    elif [ -e "$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml" ]
+        com1="$agent1.xml" ;
+    elif [ -e "$(before-dash "$agent1")".xml ] ;
     then
-        com1="$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml"
-    elif [ -e "$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml" ]
+        com1="$(before-dash "$agent1")".xml
+    elif [ -e "$(after-dash "$agent1")".xml ] ;
     then
-        com1="$(echo "$agent1" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml"
+        com1="$(after-dash "$agent1")".xml
     else
         echo "No communications configuration file found for base name $agent1"
         exit 1
@@ -193,17 +202,17 @@ then
 fi
 
 # And now for agent2
-if [ -z "$com2" ]
+if [ -z "$com2" ] ;
 then
-    if [ -e "$agent2.xml" ]
+    if [ -e "$agent2.xml" ] ;
     then
-        com2="$agent2.xml"
-    elif [ -e "$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml" ]
+        com2="$agent2.xml" ;
+    elif [ -e "$(before-dash "$agent2")".xml ] ;
     then
-        com2="$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[1]) }').xml"
-    elif [ -e "$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml" ]
+        com1="$(before-dash "$agent2")".xml
+    elif [ -e "$(after-dash "$agent2")".xml ] ;
     then
-        com2="$(echo "$agent2" | awk '{ split($0, arr, "-"); print(arr[2]) }').xml"
+        com1="$(after-dash "$agent2")".xml
     else
         echo "No communications configuration file found for base name $agent2"
         exit 1
@@ -213,8 +222,9 @@ fi
 # Now, double check to be sure we have comm configuration files
 if [ ! -e "$com1" ] ; then
     if [ ! -e "$com1.xml" ] ; then
-        echo " " ; echo "No communications configuration file found for \"-c $com1\""
+        echo ' ' ; echo "No communications configuration file found for \"-c $com1\""
         usage
+        exit 1
     else
         com1="$com1.xml"
     fi
@@ -222,21 +232,22 @@ fi
 # Now, do it again for the second agent
 if [ ! -e "$com2" ] ; then
     if [ ! -e "$com2.xml" ] ; then
-        echo " " ; echo "No communications configuration file found for \"-c $com2\""
+        echo ' ' ; echo "No communications configuration file found for \"-c $com2\""
         usage
+        exit 1
     else
         com2="$com2.xml"
     fi
 fi
 
 # For readability
-echo " "
+echo ' '
 
 # Try to figure out which make to use
 MAKE='make'
 if [ "$(uname -s)" = 'FreeBSD' ]
 then
-    if ( command -v gmake )
+    if command -v gmake
     then
 	    MAKE='gmake'
     else
@@ -255,7 +266,7 @@ else
 fi
 
 # Keep the plans up-to-date if possible...
-"${MAKE}" -f "$make_file" "$agent1.plx" "$agent2.plx"
+${MAKE} -f "$make_file" "$agent1.plx" "$agent2.plx"
 make_status=$?
 # bail if things don't compile properly
 if [ $make_status != 0 ] ;
@@ -264,27 +275,34 @@ then
     exit $make_status
 fi
 
+# FIXNE: support .ple, .plp too
+try_find_library()
+{
+    lib="$(echo "$1" | awk '{ split($0, arr, "."); print(arr[1]) }')"
+    # allow for both lib/name and just name
+    if [ -e "$lib.pli" ]
+    then
+        printf '%s\n' "$lib.pli"
+    elif [ -e "lib/$lib.pli" ]
+    then
+        printf '%s\n' "lib/$lib"
+    else
+        echo "$lib.pli not found" >&2
+        exit 1
+    fi
+}
+
 # Set up the libraries for inclusion
+# FIXME
 for lib in $libs1 ;
 do
-    lib="$(echo "$lib" | awk '{ split($0, arr, "."); print(arr[1]) }')"
-    # allow for both lib/name and just name
-    if [ ! -e "$lib.pli" ]
-    then
-        if [ -e "lib/$lib.pli" ]
-        then
-            lib="lib/$lib"
-        else
-            echo "$lib.pli not found"
-            exit
-        fi
-    fi
-    ${MAKE} "$lib.plx"
-    # stop of the compile fails
-    if [ $? != 0 ]
+    lib="$(try_find_library "$lib")"
+
+    # stop if the compile fails
+    if ! ${MAKE} "$lib.plx"
     then
         echo "Error: $lib.plx failed to compile"
-        exit
+        exit 1
     fi
     libraries1="$libraries1 -l $lib.plx"
 done
@@ -292,19 +310,10 @@ done
 # And again for the second agent
 for lib in $libs2 ;
 do
-    lib="$(echo "$lib" | awk '{ split($0, arr, "."); print(arr[1]) }')"
-    if [ ! -e "$lib.pli" ]
-    then
-        if [ -e "lib/$lib.pli" ]
-        then
-            lib="lib/$lib"
-        else
-            echo "$lib.pli not found"
-            exit 1
-        fi
-    fi
-    ${MAKE} "$lib.plx"
-    if [ $? != 0 ]
+    lib="$(try_find_library "$lib")"
+
+    # stop if the compile fails
+    if ! ${MAKE} "$lib.plx"
     then
         echo "Error: $lib.plx failed to compile"
         exit 1
@@ -314,7 +323,7 @@ done
 
 # Set up the command line and sleep time.  Java on Mac OS is really slow,
 # hence the long sleep time...
-if [ "$use_viewer" = "yes" ] ;
+if [ "$use_viewer" = 'yes' ] ;
 then
     cmd1="plexilexec -v -b -p $agent1.plx -c $com1 $libdirs1 $libraries1"
     cmd2="plexilexec -v -b -p $agent2.plx -c $com2 $libdirs2 $libraries2"
@@ -325,59 +334,59 @@ then
         sleep_time=3
     fi
 else
+    # FIXME: find another way to do this
     cmd1="plexilexec -p $agent1.plx -c $com1 $libdirs1 $libraries1"
     cmd2="plexilexec -p $agent2.plx -c $com2 $libdirs2 $libraries2"
     sleep_time=1
 fi
 
-if [ -n "$debug" ]
+if [ -n "$debug" ] ;
 then
-    echo " " 
+    echo ' '
     echo "agent1_raw:   $agent1_raw"
     echo "agent1:       $agent1"
     echo "com1:         $com1"
     echo "libs1:        $libs1"
     echo "libraries1:   $libraries1"
-    echo " " 
+    echo ' '
     echo "agent2_raw:   $agent2_raw"
     echo "agent2:       $agent2"
     echo "com2:         $com2"
     echo "libs2:        $libs2"
     echo "libraries2:   $libraries2"
-    echo " " 
+    echo ' ' 
     echo "cmd1:         $cmd1"
     echo "cmd2:         $cmd2"
-    echo " "
+    echo ' '
     echo "PLEXIL_HOME:  $PLEXIL_HOME"
     echo "make_file:    $make_file"
-    echo " "
+    echo ' '
     exit
 fi
 
 # Either start IPC/central in an xterm, or make sure it is already running
-if [ "$has_xterm" = "" ] && [ "$no_ipc" != "yes" ];
+if [ -z "$has_xterm" ] && [ "$no_ipc" != 'yes' ];
 then
-    echo " "
-    if [ "$ipc_running" = "" ] && [ "$run_ipc_in_background" = "no" ] ;
+    echo ' '
+    if [ -z "$ipc_running" ] && [ "$run_ipc_in_background" = 'no' ] ;
     then
-        echo "ipc (central) must already be running for this script to work without xterm..."
-        echo " "
-        exit 1
+        echo 'ipc (central) must already be running for this script to work without xterm...'
+        echo ' '
+        exit
     else
-        echo "xterm not found: both agents will be run in the background..."
-        echo " "
+        echo 'xterm not found: both agents will be run in the background...'
+        echo ' '
     fi
 fi
 
 # start IPC/central if necessary
-if [ "$no_ipc" != "yes" ] ;
+if [ "$no_ipc" != 'yes' ] ;
 then
-    if [ "$ipc_running" = "" ] ;
+    if [ -z "$ipc_running" ] ;
     then
         echo ' '
-        echo "Starting IPC..."
-        if [ "$run_ipc_in_background" = "no" ]
-        then
+        echo 'Starting IPC...'
+        if [ "$run_ipc_in_background" = 'no' ] ; then
             xterm -g 172x20 -T "IPC" ipc &
         else
             central -s -L -f/dev/null &
@@ -387,31 +396,37 @@ then
         fi
         sleep 3;
     else
-        echo " " ; echo "IPC already running..."
+        echo ' ' ; echo 'IPC already running...'
         run_ipc_in_background=no
     fi
 fi
 
 # Start the agents
+# FIXME
 echo "$cmd1"
 if [ "$use_xterm" = "no" ] ;
 then
     $cmd1 &
 else
+    # shellcheck disable=SC2086
+    # yes, we want word splitting for now. Needs to be fixed.
     xterm -e $cmd1 &
 fi
 
 sleep $sleep_time
 
+# FIXME
 echo "$cmd2"
 if [ "$use_xterm" = "no" ] ;
 then
     $cmd2
 else
+    # shellcheck disable=SC2086
+    # yes, we want word splitting for now. Needs to be fixed.
     xterm -e $cmd2
 fi
 
-if [ "$run_ipc_in_background" = "yes" ] && [ "$no_ipc" != "yes" ];
+if [ "$run_ipc_in_background" = 'yes' ] && [ "$no_ipc" != 'yes' ];
 then
     kill -9 "$ipc_pid"
     echo ' '
